import {test,expect,_electron,type ElectronApplication} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {seedProject} from '../../src/shared/game/seed.js';
import {newActor,newBubble,newCinematic,newShot,type Asset} from '../../src/shared/model.js';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const asset:Asset={ref:'library://05_characters/test.png',path:'05_characters/test.png',name:'Rose',folder:'05_characters',kind:'character',bytes:1,modified:0,url:'',thumbnail:''};

test('copy characters and dialogue bubbles between plans with identical geometry',async({},info)=>{
 test.setTimeout(90000);
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'lunaria-copy-'));
 const projectFile=path.join(dir,'lunaria.game.json'),profile=path.join(dir,'profile'),library=path.join(dir,'library');
 let app:ElectronApplication|undefined;
 try{
  await fs.mkdir(profile);await fs.mkdir(path.join(library,'05_characters'),{recursive:true});
  await fs.copyFile(path.join(ROOT,'example-library','06_ui','dialogues','tooltip_ornate_v01.png'),path.join(library,'05_characters','test.png'));
  await fs.writeFile(path.join(profile,'settings.json'),JSON.stringify({libraryRoot:library}));
  const film=newCinematic(),source=film.shots[0],destination=newShot();
  source.name='Plan source';destination.name='Plan destination';film.shots.push(destination);
  const rose=newActor(asset,1.5,.137,.523);rose.width=.219;rose.height=.491;rose.flipX=true;
  source.actors.push(rose);
  const dialogue=newBubble(rose.id);dialogue.text='Bonjour depuis le plan source.';dialogue.x=.217;dialogue.y=.139;dialogue.width=.427;dialogue.height=.183;
  source.bubbles.push(dialogue);
  const project=seedProject();project.levels=[];project.campaign={steps:[],cinematics:[]};project.cinematics=[film];
  await fs.writeFile(projectFile,JSON.stringify(project));
  const env={...process.env,LUNARIA_E2E:'1',LUNARIA_TEST_USER_DATA:profile};delete env.LUNARIA_DEV_URL;
  app=await _electron.launch({args:[ROOT],env:env as Record<string,string>});
  const page=await app.firstWindow();await page.waitForURL('app://studio/index.html');
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},projectFile);
  await page.getByRole('button',{name:'Ouvrir le projet'}).click();
  await expect(page.getByLabel('Nom du plan')).toHaveValue('Plan source');
  await page.getByRole('button',{name:'Sélectionner Rose'}).click();
  await page.getByRole('button',{name:'Copier le personnage'}).click();
  await page.getByRole('button',{name:'Fermer le message'}).click();
  await page.keyboard.press('Control+c');
  await expect(page.locator('.toast')).toContainText('copié');
  await page.getByTestId('shot-card-1').click();
  await expect(page.getByRole('button',{name:'Coller ici'})).toBeVisible();
  await page.getByRole('button',{name:'Coller ici'}).click();
  await expect(page.getByRole('button',{name:'Sélectionner Rose'})).toBeVisible();
  await page.keyboard.press('Control+z');
  await expect(page.getByRole('button',{name:'Sélectionner Rose'})).toHaveCount(0);
  await page.keyboard.press('Control+v');
  await expect(page.getByRole('button',{name:'Sélectionner Rose'})).toBeVisible();
  await page.screenshot({path:info.outputPath('character-copy.png')});
  await page.getByRole('button',{name:'Enregistrer le projet'}).click();
  await expect.poll(async()=>JSON.parse(await fs.readFile(projectFile,'utf8')).cinematics[0].shots[1].actors.length).toBe(1);
  const saved=JSON.parse(await fs.readFile(projectFile,'utf8')).cinematics[0].shots;
  expect(saved[1].actors[0]).toMatchObject({name:'Rose',x:.137,y:.523,width:.219,height:.491,flipX:true});
  expect(saved[1].actors[0].id).not.toBe(saved[0].actors[0].id);
  expect(saved[0].actors[0]).toMatchObject({x:.137,y:.523,width:.219,height:.491});
  await page.getByTestId('shot-card-0').click();
  await page.locator('.layer-row[data-role="bubble"] .layer-select').click();
  await page.getByRole('button',{name:'Copier la bulle'}).click();
  await page.getByTestId('shot-card-1').click();
  await expect(page.getByRole('button',{name:'Coller la bulle'})).toBeVisible();
  await page.keyboard.press('Control+v');
  await expect(page.locator('.layer-row[data-role="bubble"]')).toHaveCount(1);
  await page.screenshot({path:info.outputPath('bubble-copy.png')});
  await page.getByRole('button',{name:'Enregistrer le projet'}).click();
  await expect.poll(async()=>JSON.parse(await fs.readFile(projectFile,'utf8')).cinematics[0].shots[1].bubbles.length).toBe(1);
  const withBubble=JSON.parse(await fs.readFile(projectFile,'utf8')).cinematics[0].shots;
  expect(withBubble[1].bubbles[0]).toMatchObject({text:dialogue.text,x:.217,y:.139,width:.427,height:.183,speakerId:withBubble[1].actors[0].id});
  expect(withBubble[1].bubbles[0].id).not.toBe(withBubble[0].bubbles[0].id);
 }finally{await app?.close();await fs.rm(dir,{recursive:true,force:true});}
});
