import {test,expect,_electron,type ElectronApplication} from '@playwright/test';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {seedProject} from '../../src/shared/game/seed.js';
import {newLevel} from '../../src/shared/game/types.js';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
test('Cigarette: inspect art, edit souffle cells, assign a wave, save and reopen',async({},info)=>{
 const temp=await fs.mkdtemp(path.join(os.tmpdir(),'lunaria-cigarette-e2e-')),profile=path.join(temp,'profile'),target=path.join(temp,'cigarette.game.json');
 let app:ElectronApplication|undefined;
 try{
  await fs.mkdir(profile);await fs.writeFile(path.join(profile,'settings.json'),JSON.stringify({libraryRoot:'C:/dev/Lunaria/LunariaArtLibrary'}));
  const project=seedProject();project.levels=[newLevel(['radish','rose'],'cigarette')];
  project.campaign={steps:[{id:'step_cigarette_ui',kind:'level',levelId:project.levels[0].id}],cinematics:[]};
  await fs.writeFile(target,JSON.stringify(project));
  const env=Object.fromEntries(Object.entries(process.env).filter((entry):entry is [string,string]=>typeof entry[1]==='string'));delete env.LUNARIA_DEV_URL;
  app=await _electron.launch({args:[ROOT],env:{...env,LUNARIA_E2E:'1',LUNARIA_TEST_USER_DATA:profile}});
  const page=await app.firstWindow();await page.waitForURL('app://studio/index.html');
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},target);
  await page.locator('.studio-modebar').getByRole('button',{name:/^Niveaux/}).click();
  await page.locator('.gd-toolbar').getByRole('button',{name:'Ouvrir',exact:true}).click();
  await expect(page.locator('.gd-message')).toContainText('Projet ouvert.');
  await page.locator('.gd-sections').getByRole('button',{name:/^Ennemis/}).click();
  await page.getByRole('complementary',{name:'Catalogue des ennemis'}).getByRole('button',{name:/^Cigarette/}).click();
  await expect(page.getByRole('heading',{name:'Cigarette',exact:true})).toBeVisible();
  await expect(page.getByLabel('Points de vie',{exact:true})).toHaveValue('220');
  await expect(page.getByLabel('Type de dégâts',{exact:true})).toHaveValue('toxic');
  const art=page.getByRole('region',{name:'Image principale de Cigarette'}).getByRole('img',{name:'Cigarette combat · v1',exact:true});
  await expect(art).toBeVisible();await expect(art.locator('svg image')).toHaveAttribute('width','1254');
  await page.screenshot({path:info.outputPath('cigarette-studio-enemy.png')});
  await page.getByRole('button',{name:'Animations de Cigarette',exact:true}).click();
  await page.locator('.lp-owned-list').getByRole('button',{name:/^Cigarette — souffle/}).click();
  await expect(page.getByLabel('Style de l’animation')).toHaveValue('frames');
  await expect(page.getByLabel('Images de l’animation').getByRole('button')).toHaveCount(8);
  await page.getByLabel('Curseur temporel de l’animation').fill('0.35');
  await expect(page.locator('.lp-owned-editor .lp-preview svg image').first()).toHaveAttribute('width','1536');
  await page.getByRole('heading',{name:'Cigarette — souffle',exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:info.outputPath('cigarette-studio-animation.png')});
  await page.getByRole('button',{name:'Caractéristiques et attaques',exact:true}).click();
  await page.getByRole('button',{name:'Modifier cette attaque →'}).click();
  await expect(page.getByRole('heading',{name:'Souffle de fumée',exact:true})).toBeVisible();
  await expect(page.getByLabel('Zone de ciblage')).toHaveValue('cells');
  await expect(page.getByLabel('Nombre de cases devant')).toHaveValue('3');
  await page.getByLabel('Intervalle entre utilisations (s)').fill('2.8');await page.getByLabel('Intervalle entre utilisations (s)').press('Tab');
  await page.screenshot({path:info.outputPath('cigarette-studio-attack.png')});

  await page.locator('.studio-modebar').getByRole('button',{name:'Enregistrer le projet'}).click();
  await expect.poll(async()=>JSON.parse(await fs.readFile(target,'utf8')).combat.abilities.find((a:any)=>a.id==='ab_cigarette_smoke').cooldown).toBe(2.8);
  await page.locator('.gd-sections').getByRole('button',{name:/^Niveaux/}).click();
  await page.getByRole('button',{name:'Vagues & ennemis'}).click();
  await expect(page.getByLabel('Ennemi du groupe 1')).toHaveValue('cigarette');
  await page.getByLabel('Ennemi du groupe 1').selectOption('runner');await page.getByLabel('Ennemi du groupe 1').selectOption('cigarette');
  await page.locator('.studio-modebar').getByRole('button',{name:'Enregistrer le projet'}).click();
  await page.locator('.gd-toolbar').getByRole('button',{name:'Ouvrir',exact:true}).click();await expect(page.locator('.gd-message')).toContainText('Projet ouvert.');
  await expect.poll(async()=>JSON.parse(await fs.readFile(target,'utf8')).levels[0].waves[0].groups[0].enemyId).toBe('cigarette');
  await page.locator('.gd-sections').getByRole('button',{name:/^Ennemis/}).click();
  await page.getByRole('complementary',{name:'Catalogue des ennemis'}).getByRole('button',{name:/^Cigarette/}).click();
  await page.getByRole('button',{name:'Modifier cette attaque →'}).click();
  await expect(page.getByLabel('Intervalle entre utilisations (s)')).toHaveValue('2.8');
  await expect(page.getByLabel('Nombre de cases devant')).toHaveValue('3');
  await page.getByLabel('Intervalle entre utilisations (s)').fill('2.4');await page.getByLabel('Intervalle entre utilisations (s)').press('Tab');
  await page.getByLabel('Nombre de cases devant').scrollIntoViewIfNeeded();
  await page.locator('.gd-message button').click();
  await page.screenshot({path:info.outputPath('cigarette-studio-attack.png')});
  // Inspect the authoritative project with its real art; no save/mutation follows this read.
  await page.locator('.studio-modebar').getByRole('button',{name:'Enregistrer le projet'}).click();
  await expect.poll(async()=>JSON.parse(await fs.readFile(target,'utf8')).combat.abilities.find((a:any)=>a.id==='ab_cigarette_smoke').cooldown).toBe(2.4);
  await app.evaluate(({dialog})=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:['C:/dev/Lunaria/HISTOIRE DE LUNARIA/Cinematiques studio/lunaria.game.json']});});
  await page.locator('.gd-toolbar').getByRole('button',{name:'Ouvrir',exact:true}).click();
  await expect(page.locator('.gd-message')).toContainText('Projet ouvert.');
  await page.locator('.gd-sections').getByRole('button',{name:/^Ennemis/}).click();
  await page.getByRole('complementary',{name:'Catalogue des ennemis'}).getByRole('button',{name:/^Cigarette/}).click();
  await page.getByRole('button',{name:'Animations de Cigarette',exact:true}).click();
  await page.locator('.lp-owned-list').getByRole('button',{name:/^Cigarette — souffle/}).click();
  await expect(page.getByLabel('Images de l’animation').getByRole('button')).toHaveCount(8);
  await page.getByLabel('Curseur temporel de l’animation').fill('0.35');
  await expect(page.locator('.lp-owned-editor .lp-preview svg image').first()).toHaveAttribute('width','1536');
  await page.getByRole('heading',{name:'Cigarette — souffle',exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:info.outputPath('cigarette-studio-authoritative.png')});
  await page.locator('.gd-message button').click();
  await page.locator('.lp-owned-editor .lp-preview').getByLabel('Ancrages',{exact:true}).uncheck();
  await page.locator('.lp-owned-editor .lp-preview').screenshot({path:info.outputPath('cigarette-studio-souffle-preview.png')});
  await page.getByLabel('Images de l’animation').screenshot({path:info.outputPath('cigarette-studio-eight-frames.png')});
  await page.locator('.lp-owned-list').getByRole('button',{name:/^Cigarette — touchée/}).click();
  await expect(page.getByLabel('Images de l’animation').getByRole('button')).toHaveCount(4);
  await expect(page.getByLabel('Curseur temporel de l’animation')).toHaveAttribute('max','0.4');
  await page.getByLabel('Curseur temporel de l’animation').fill('0.1');
  await expect(page.locator('.lp-owned-editor .lp-preview svg image').first()).toHaveAttribute('width','1254');
  await page.locator('.lp-owned-editor .lp-preview').screenshot({path:info.outputPath('cigarette-studio-hit-preview.png')});
  await page.locator('.gd-sections').getByRole('button',{name:/^Comportements/}).click();
  await page.locator('.gd-catalog').getByRole('button',{name:/^Cigarette — avance au contact/}).click();
  await expect(page.getByLabel('S’arrêter quand une cible adverse est à portée')).not.toBeChecked();
  await expect(page.getByLabel('Déplacement par défaut')).toHaveValue('advance');
  await expect(page.getByLabel('Décision du comportement')).toContainText('Mouvement : Avancer');
  await page.getByLabel('Attaques prêtes',{exact:true}).uncheck();
  await expect(page.getByLabel('Décision du comportement')).toContainText('Mouvement : Avancer');
  await page.getByLabel('Nom du comportement').scrollIntoViewIfNeeded();
  await page.screenshot({path:info.outputPath('cigarette-studio-contact.png')});
 }finally{
  if(app){await app.evaluate(({BrowserWindow})=>{for(const window of BrowserWindow.getAllWindows())window.destroy();}).catch(()=>undefined);await app.close();}
  await fs.rm(temp,{recursive:true,force:true});
 }
});
