import {test,expect,_electron,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
let app:ElectronApplication,page:Page,dir:string,file:string;
test.beforeEach(async()=>{
 dir=await fs.mkdtemp(path.join(os.tmpdir(),'lunaria-friendly-e2e-'));file=path.join(dir,'mon-projet.game.json');
 const env={...process.env,LUNARIA_E2E:'1',LUNARIA_TEST_USER_DATA:path.join(dir,'profile')};delete env.LUNARIA_DEV_URL;
 app=await _electron.launch({args:[ROOT],env:env as Record<string,string>});page=await app.firstWindow();
 await page.waitForURL('app://studio/index.html');await page.setViewportSize({width:1462,height:900});
 await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});dialog.showMessageBox=async()=>({response:1,checkboxChecked:false});},file);
 await expect(page.locator('.studio-save')).toBeEnabled();
});
test.afterEach(async()=>{await app?.close();await fs.rm(dir,{recursive:true,force:true});});

test('project overview guides creation and saves levels and films together',async({},info)=>{
 await page.getByRole('button',{name:'Vue du projet',exact:true}).click();
 let overview=page.getByRole('dialog',{name:'Vue du projet'});
 await expect(overview).toContainText('0 cinématique dans le projet');
 await expect(overview).toContainText('0 niveau dans le projet');
 await page.screenshot({path:info.outputPath('overview.png')});
 await overview.getByRole('button',{name:/Créer un niveau/}).click();
 await expect(overview).not.toBeVisible();
 await page.getByLabel('Nom du niveau').fill('Le jardin des débuts');
 await page.getByRole('button',{name:'Vue du projet',exact:true}).click();
 overview=page.getByRole('dialog',{name:'Vue du projet'});
 await expect(overview).toContainText('1 niveau dans le projet');
 await expect(overview).toContainText('1 étape dans le parcours');
 await overview.getByRole('button',{name:/Créer une cinématique/}).click();
 await page.getByLabel('Titre de la cinématique').fill('Avant le jardin');
 await page.getByRole('button',{name:'Vue du projet',exact:true}).click();
 await page.getByRole('dialog',{name:'Vue du projet'}).getByRole('button',{name:'Enregistrer',exact:true}).click();
 await expect.poll(async()=>{try{return JSON.parse(await fs.readFile(file,'utf8')).cinematics?.[0]?.title;}catch{return '';}}).toBe('Avant le jardin');
 const saved=JSON.parse(await fs.readFile(file,'utf8'));expect(saved.levels[0].title).toBe('Le jardin des débuts');
 await expect(page.locator('.studio-project-state')).toContainText('Projet enregistré');
 await page.getByRole('button',{name:'Vue du projet',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Vue du projet'})).toContainText('Toutes les modifications sont enregistrées');
 await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Vue du projet',exact:true})).toBeFocused();
 await page.getByLabel('Titre de la cinématique').fill('Film enregistré au clavier');
 await page.getByRole('button',{name:'Vue du projet',exact:true}).click();
 await page.getByRole('dialog',{name:'Vue du projet'}).getByRole('button',{name:'Fermer',exact:true}).focus();
 await page.keyboard.press('Control+s');
 await expect.poll(async()=>JSON.parse(await fs.readFile(file,'utf8')).cinematics[0].title).toBe('Film enregistré au clavier');
 await expect(page.locator('.studio-save')).toBeEnabled();
});

test('compact tools and searchable catalogs keep the editor usable on a small screen',async({},info)=>{
 await page.locator('.studio-modebar').getByRole('button',{name:'Niveaux',exact:true}).click();
 await page.getByRole('button',{name:'Créer un premier niveau',exact:true}).click();
 await expect(page.getByLabel('Nom du niveau')).toBeVisible();
 await page.getByLabel('Rechercher un niveau').fill('absent');
 await expect(page.getByText('Aucun niveau ne correspond à ces filtres.')).toBeVisible();
 await page.getByRole('button',{name:'Effacer les filtres'}).click();
 await expect(page.locator('.gd-level-items button')).toHaveCount(1);
 await page.getByLabel('Rechercher un niveau').fill('absent');
 await page.getByRole('button',{name:'+ Créer un niveau',exact:true}).click();
 await expect(page.getByLabel('Rechercher un niveau')).toHaveValue('');
 await expect(page.locator('.gd-level-items button')).toHaveCount(2);
 await page.locator('.gd-sections').getByRole('button',{name:/Plantes alliées/}).click();
 await page.getByLabel('Rechercher un personnage').fill('aloes');
 await expect(page.locator('.gd-catalog > button')).toHaveCount(1);
 await page.locator('.gd-catalog > button').click();
 await expect(page.getByRole('heading',{name:'Aloès',exact:true})).toBeVisible();
 await page.getByLabel('Rechercher un personnage').fill('inexistant');
 await page.getByRole('button',{name:'Effacer la recherche'}).click();
 await expect(page.locator('.gd-catalog > button')).toHaveCount(29);
 await page.setViewportSize({width:1000,height:720});
 expect(await page.locator('.gd-body').evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(440);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(1000);
 await expect(page.locator('.lp-character-image .lp-image-preview')).toHaveCount(1);
 await expect(page.getByRole('button',{name:'Caractéristiques et attaques'})).toBeInViewport();
 await expect(page.locator('.lp-navigation')).not.toBeVisible();
 await page.screenshot({path:info.outputPath('small-editor.png')});
 await page.locator('.gd-tools > summary').click();
 await expect(page.locator('.lp-navigation')).toBeVisible();
 await page.locator('.gd-tools > summary').click();
 await page.locator('.gd-delivery > summary').click();
 await expect(page.getByRole('button',{name:'Exporter pour Android'})).toBeVisible();
 await page.screenshot({path:info.outputPath('export-menu.png')});
 await page.keyboard.press('Escape');
 await expect(page.locator('.gd-delivery')).not.toHaveAttribute('open','');
});

test('blocking validation explains the problem and returns to the invalid field',async()=>{
 await page.locator('.studio-modebar').getByRole('button',{name:'Niveaux',exact:true}).click();
 await page.getByRole('button',{name:'Créer un premier niveau',exact:true}).click();
 await page.getByLabel('Nom du niveau').fill('');
 await page.locator('.gd-delivery > summary').click();
 await expect(page.getByRole('button',{name:'Publier la campagne',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:/point.*à corriger avant de continuer/}).click();
 const dialog=page.getByRole('dialog',{name:'Vérifier le projet'});
 await expect(dialog).toBeVisible();
 await dialog.getByRole('button',{name:/Longueur de texte invalide/}).click();
 await expect(dialog).not.toBeVisible();
 await expect(page.getByLabel('Nom du niveau')).toBeFocused();
 await page.getByLabel('Nom du niveau').fill('Jardin réparé');
 await page.locator('.gd-delivery > summary').click();
 await expect(page.getByRole('button',{name:'Publier la campagne',exact:true})).toBeEnabled();
});
