import test from 'node:test';
import assert from 'node:assert/strict';
import {newActor, newBubble, newCinematic, copy, duplicateShot, hasV3Features, upgradeCinematicFormat,
  type ActorRole, type Asset, type TextReveal, type TextEffect, type MotionPreset, type EntryPreset, type ExitPreset} from '../src/shared/model.js';
import {graphemes, unitsForLines} from '../src/shared/textSegments.js';
import {autoDialogueDuration, bubbleTextUnits, glyphPose, fitGlyphPose, newTextAnimation, textIntroDuration, textNeedsCompletion} from '../src/shared/textAnimation.js';
import {beginPlayback, tickPlayback, advanceDialogue} from '../src/shared/playback.js';
import {newMotion, newMovement, actorPose, actorAnchor, restPose} from '../src/shared/motion.js';
import {bubbleLayout, prepareCinematic, wrapText} from '../src/shared/geometry.js';
import {parseCinematic, validationIssues} from '../src/shared/schema.js';
import {editCommand} from '../src/shared/commands.js';
import {createHistory, historyReducer} from '../src/shared/history.js';
import {createTemplate} from '../src/shared/studio.js';
import {diagnose} from '../src/shared/diagnostics.js';
const source: Asset = {ref:'library://07_props/lamp.png', path:'07_props/lamp.png', folder:'07_props', name:'Lampe',kind:'prop',bytes:1,modified:0,url:'x',thumbnail:'x'};
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function scene() {const d=newCinematic();d.shots[0].duration=1;d.shots[0].dialogueStart=0;d.shots[0].transition={type:'cut',duration:0};const b=newBubble();b.text='Bonjour !';b.textAnimation={...newTextAnimation(),speed:10};d.shots[0].bubbles=[b];return {d,b,s:d.shots[0]};}
function firstGlyph(b:ReturnType<typeof newBubble>,time:number,complete=false) {return glyphPose(b,bubbleTextUnits(b)[0],time,30,20,500,90,complete);}

test('V1.5 never upgrades an untouched v1 document',()=>assert.equal(prepareCinematic(newCinematic()).schemaVersion,1));
test('v2 actor effects remain v2',()=>{const d=newCinematic();d.shots[0].actors=[newActor(source,1)];d.shots[0].actors[0].motion=newMotion('float');assert.equal(prepareCinematic(d).schemaVersion,2);});
test('animated text requires v3 and round-trips without rewriting the text',()=>{const {d,b}=scene();const original=JSON.stringify(d);assert.ok(validationIssues(d).some(s=>s.includes('schemaVersion: 3')));const ready=prepareCinematic(d);assert.equal(ready.schemaVersion,3);const out=parseCinematic(JSON.parse(JSON.stringify(ready)));assert.deepEqual(out.shots[0].bubbles[0].textAnimation,b.textAnimation);assert.equal(out.shots[0].bubbles[0].text,b.text);assert.equal(JSON.stringify(d),original);});
test('v3 is never downgraded when an effect is removed',()=>{const d=newCinematic();d.schemaVersion=3;d.shots[0].actors=[newActor(source,1)];upgradeCinematicFormat(d);assert.equal(d.schemaVersion,3);});
test('animation change is undoable and restores the older format',()=>{const d=newCinematic();d.shots[0].bubbles=[newBubble()];let h=createHistory(d);h=historyReducer(h,{type:'execute',command:editCommand(d,n=>{n.shots[0].bubbles[0].textAnimation=newTextAnimation();upgradeCinematicFormat(n);},'Animer le texte')});assert.equal(h.present.schemaVersion,3);h=historyReducer(h,{type:'undo'});assert.equal(h.present.schemaVersion,1);assert.equal(h.present.shots[0].bubbles[0].textAnimation,undefined);h=historyReducer(h,{type:'redo'});assert.equal(h.present.schemaVersion,3);});
test('duplicate plan keeps animation settings but remaps identities',()=>{const {s,b}=scene();const a=newActor(source,1);a.exit={preset:'fade',start:4,duration:1};s.actors=[a];b.speakerId=a.id;const out=duplicateShot(s);assert.deepEqual(out.bubbles[0].textAnimation,b.textAnimation);assert.deepEqual(out.actors[0].exit,a.exit);assert.equal(out.bubbles[0].speakerId,out.actors[0].id);assert.notEqual(out.actors[0].id,a.id);});
for(const [field,value] of [['reveal','eval'],['effect','unknown'],['speed',0],['speed',NaN],['speed',121],['duration',0],['duration',11],['delay',-1],['delay',31],['intensity',-0.1],['intensity',1.1],['loop','yes']] as const) test(`reject invalid text animation ${field}=${value}`,()=>{const {d,b}=scene();d.schemaVersion=3;(b.textAnimation as unknown as Record<string,unknown>)[field]=value;assert.ok(validationIssues(d).length);});
for(const reveal of ['instant','typewriter','words','fade'] as TextReveal[])for(const effect of ['none','shout','wave','shake','bounce'] as TextEffect[])test(`schema supports reveal ${reveal} + ${effect}`,()=>{const {d,b}=scene();b.textAnimation=newTextAnimation(reveal,effect);assert.deepEqual(validationIssues(prepareCinematic(d)),[]);});

test('graphemes keep accents, surrogate pairs and joined emoji intact',()=>assert.deepEqual(graphemes('e\u0301🌱👩🏽‍🌾🇫🇷'),['e\u0301','🌱','👩🏽‍🌾','🇫🇷']));
test('wrapping long words cannot sever a grapheme',()=>{const lines=wrapText('e\u0301👩🏽‍🌾🇫🇷',1,28);assert.deepEqual(lines,['e\u0301','👩🏽‍🌾','🇫🇷']);});
test('word groups follow explicit lines and apostrophes',()=>{const u=unitsForLines(['L’été arrive.','Vraiment ?']);assert.equal(Math.max(...u.map(x=>x.word)),3);assert.equal(u.filter(x=>x.text==='\n').length,1);});
test('unit cache invalidates after editing text and width',()=>{const {b}=scene();const u=bubbleTextUnits(b);b.text='Nouveau texte plus long';assert.notEqual(bubbleTextUnits(b),u);const v=bubbleTextUnits(b);b.width=.07;assert.notEqual(bubbleTextUnits(b),v);});
test('typewriter starts empty and reveals exactly one complete grapheme',()=>{const {b}=scene();b.text='e\u0301🌱';b.textAnimation!.speed=2;assert.equal(firstGlyph(b,0).opacity,0);assert.equal(firstGlyph(b,.499).opacity,0);assert.equal(firstGlyph(b,.5).opacity,1);const u=bubbleTextUnits(b);assert.equal(glyphPose(b,u[1],.5,80,20,500,80).opacity,0);assert.equal(glyphPose(b,u[1],1,80,20,500,80).opacity,1);close(textIntroDuration(b),1);});
test('words are revealed as whole reading groups',()=>{const {b}=scene();b.text='Rose ! Radis !';b.textAnimation=newTextAnimation('words');b.textAnimation.speed=2;const visible=bubbleTextUnits(b).filter(u=>glyphPose(b,u,.5,10,20,400,80).opacity>0).map(u=>u.text).join('');assert.equal(visible,'Rose ');close(textIntroDuration(b),2);});
test('delayed fade starts invisible and finishes fully visible',()=>{const {b}=scene();b.textAnimation={...newTextAnimation('fade'),delay:1,duration:2};assert.equal(firstGlyph(b,.5).opacity,0);close(firstGlyph(b,2).opacity,.5);close(firstGlyph(b,3).opacity,1);close(textIntroDuration(b),3);});
test('fixed bubble geometry is not affected by reveal or expressive effects',()=>{const {b}=scene();const l=bubbleLayout(b);b.textAnimation=newTextAnimation('instant','shout');for(const time of [0,.1,.5,3])firstGlyph(b,time);assert.deepEqual(bubbleLayout(b),l);});
test('shout expands then returns to a readable rest state',()=>{const {b}=scene();b.textAnimation=newTextAnimation('instant','shout');const hit=firstGlyph(b,.65*.24);assert.ok(hit.scale>1);assert.notEqual(hit.rotation,0);assert.notEqual(hit.dx,0);assert.deepEqual(firstGlyph(b,.65),{opacity:1,dx:0,dy:0,rotation:0,scale:1});});
test('shout never loops even in hand-authored data',()=>{const {b}=scene();b.textAnimation={...newTextAnimation('instant','shout'),loop:true};assert.equal(firstGlyph(b,2).scale,1);assert.equal(textNeedsCompletion(b,.1),true);assert.equal(firstGlyph(b,.1,true).scale,1);});
for(const effect of ['wave','shake','bounce'] as TextEffect[])test(`${effect} is deterministic, seekable and can return to rest`,()=>{const {b}=scene();b.textAnimation=newTextAnimation('instant',effect);const before=copy(b);const p=firstGlyph(b,.38);assert.deepEqual(firstGlyph(b,.38),p);assert.notEqual(p.dy,0);assert.deepEqual(b,before);b.textAnimation.loop=false;assert.equal(firstGlyph(b,2).dy,0);});
test('completing a reveal does not stop a requested looping effect',()=>{const {b}=scene();b.textAnimation=newTextAnimation('typewriter','wave');assert.equal(firstGlyph(b,.15,true).opacity,1);assert.notEqual(firstGlyph(b,.15,true).dy,0);});
test('empty text never adds an invisible delay',()=>{const {b}=scene();b.text=' \n ';b.textAnimation!.delay=30;assert.equal(textIntroDuration(b),0);assert.equal(textNeedsCompletion(b,0),false);});
test('negative and non-finite times are safe',()=>{const {b}=scene();for(const t of [NaN,-50,Infinity])assert.equal(firstGlyph(b,t).opacity,0);});

test('first click reveals the text without changing the shot or dialogue clock',()=>{const {d}=scene();let p=tickPlayback(d,beginPlayback(),.2);const clicked=advanceDialogue(d,p);assert.equal(clicked.dialogueIndex,0);assert.equal(clicked.textCompletedAt,.2);assert.equal(clicked.elapsed,p.elapsed);assert.equal(clicked.dialogueElapsed,p.dialogueElapsed);const second=advanceDialogue(d,clicked);assert.equal(second.dialogueIndex,1);assert.equal(second.textCompletedAt,undefined);});
test('a click after completion advances immediately',()=>{const {d}=scene();const p=tickPlayback(d,beginPlayback(),1.2);assert.equal(advanceDialogue(d,p).dialogueIndex,1);});
test('paused and pre-dialogue clicks never reveal or advance',()=>{const {d,s}=scene();s.dialogueStart=.5;let p=beginPlayback();assert.equal(advanceDialogue(d,p),p);p={...p,paused:true,elapsed:1};assert.equal(advanceDialogue(d,p),p);});
test('automatic reading holds for reveal plus the configured reading time',()=>{const {d,b}=scene();b.advance={mode:'auto',seconds:2};close(textIntroDuration(b),.9);close(autoDialogueDuration(b),2.9);let p=tickPlayback(d,beginPlayback(),2.8);assert.equal(p.finished,false);assert.equal(p.dialogueIndex,0);p=tickPlayback(d,p,.1);assert.equal(p.finished,true);});
test('revealing early starts the auto reading hold at that click, without time jump',()=>{const {d,b}=scene();b.advance={mode:'auto',seconds:2};let p=tickPlayback(d,beginPlayback(),.2);p=advanceDialogue(d,p);assert.equal(p.textCompletedAt,.2);p=tickPlayback(d,p,1.99);assert.equal(p.finished,false);p=tickPlayback(d,p,.01);assert.equal(p.finished,true);});
test('next bubble gets a fresh clock and does not inherit reveal completion',()=>{const {d,s,b}=scene();s.duration=5;const second=copy(b);second.id='second';s.bubbles.push(second);let p=tickPlayback(d,beginPlayback(),.2);p=advanceDialogue(d,p);p=advanceDialogue(d,p);assert.equal(p.dialogueIndex,1);assert.equal(p.dialogueElapsed,0);assert.equal(p.textCompletedAt,undefined);assert.equal(textNeedsCompletion(second,p.dialogueElapsed),true);});
test('large-delta playback matches fine ticks across animated dialogues and shots',()=>{const {d,b,s}=scene();b.advance={mode:'auto',seconds:.5};s.bubbles.push({...copy(b),id:'second',textAnimation:newTextAnimation('fade')});d.shots.push({...duplicateShot(s),duration:10});let fine=beginPlayback();for(let i=0;i<321;i++)fine=tickPlayback(d,fine,.01);const coarse=tickPlayback(d,beginPlayback(),3.21);assert.equal(fine.shotIndex,coarse.shotIndex);assert.equal(fine.dialogueIndex,coarse.dialogueIndex);close(fine.elapsed,coarse.elapsed);close(fine.dialogueElapsed,coarse.dialogueElapsed);});
test('unanimated dialogues keep their legacy automatic duration',()=>{const {d,b}=scene();delete b.textAnimation;b.advance={mode:'auto',seconds:.8};const p=tickPlayback(d,beginPlayback(),.8);assert.equal(p.dialogueIndex,1);assert.equal(p.finished,false);assert.equal(autoDialogueDuration(b),.8);});
test('looping text cannot block automatic progression indefinitely',()=>{const {d,b}=scene();b.textAnimation=newTextAnimation('instant','wave');b.advance={mode:'auto',seconds:.5};assert.equal(tickPlayback(d,beginPlayback(),2).finished,true);});

for(const role of ['character','enemy','prop'] as ActorRole[])for(const preset of ['nod','recoil','heartbeat','flutter'] as MotionPreset[])test(`${role} supports ${preset} with a v3 roundtrip`,()=>{const d=newCinematic();const a=newActor(source,1,.4,.3,role);a.motion={...newMotion(preset),intensity:1};d.shots[0].actors=[a];assert.equal(hasV3Features(d),true);const saved=prepareCinematic(d);assert.equal(saved.schemaVersion,3);assert.deepEqual(validationIssues(saved),[]);const rest=restPose(a),moving=actorPose(a,a.motion.period*.2);assert.notDeepEqual(moving,rest);const end=actorPose({...a,motion:{...a.motion,loop:false}},a.motion.period);for(const k of ['x','y','rotation','scale'] as const)close(end[k],rest[k]);});
for(const preset of ['top','pop','zoom'] as EntryPreset[])test(`${preset} entry starts off-stage or invisible and ends at the composition`,()=>{const d=newCinematic(),a=newActor(source,1);a.entry={preset,delay:.5,duration:1};d.shots[0].actors=[a];assert.equal(prepareCinematic(d).schemaVersion,3);assert.equal(actorPose(a,.2).opacity,0);assert.deepEqual(actorPose(a,2),restPose(a));if(preset==='pop')assert.ok(actorPose(a,1.2).scale>1);});
for(const preset of ['fade','left','right','top','bottom','shrink'] as ExitPreset[])test(`${preset} exit is continuous, deterministic and stays invisible`,()=>{const d=newCinematic(),a=newActor(source,1);a.exit={preset,start:2,duration:1};a.movement={...newMovement(a),duration:6};a.motion=newMotion('sway');d.shots[0].actors=[a];const without=copy(a);delete without.exit;assert.deepEqual(actorPose(a,2),actorPose(without,2));assert.equal(actorPose(a,3).opacity,0);assert.equal(actorPose(a,30).opacity,0);assert.deepEqual(actorPose(a,2.5),actorPose(a,2.5));assert.equal(prepareCinematic(d).schemaVersion,3);});
test('disabled exit never changes a legacy pose',()=>{const a=newActor(source,1),legacy=copy(a);a.exit={preset:'none',start:0,duration:1};assert.deepEqual(actorPose(a,5),actorPose(legacy,5));});
test('tail anchors follow new entry scale and exit movement',()=>{const a=newActor(source,1);a.entry={preset:'zoom',duration:1,delay:0};a.exit={preset:'right',start:2,duration:1};assert.notDeepEqual(actorAnchor(a,.5),actorAnchor(a,1));assert.ok(actorAnchor(a,2.5).x>actorAnchor(a,2).x);});
test('impact direction follows mirroring',()=>{const a=newActor(source,1);a.motion={...newMotion('recoil'),intensity:1};const t=a.motion.period/2;assert.ok(actorPose(a,t).x<restPose(a).x);a.flipX=true;assert.ok(actorPose(a,t).x>restPose(a).x);});
for(const [key,val] of [['preset','run_code'],['duration',0],['duration',11],['start',-1],['start',301]] as const)test(`invalid exit ${key} is rejected`,()=>{const d=newCinematic(),a=newActor(source,1);a.exit={preset:'fade',start:2,duration:1};(a.exit as unknown as Record<string,unknown>)[key]=val;d.shots[0].actors=[a];d.schemaVersion=3;assert.ok(validationIssues(d).length);});
test('text effects never add duplicated assets or executable markup',()=>{const {d,b}=scene();b.text='<script>alert("bonjour")</script> [wave]texte[/wave]';const out=prepareCinematic(d);assert.equal(out.shots[0].bubbles[0].text,b.text);assert.deepEqual(validationIssues(out),[]);assert.ok(!JSON.stringify(out).includes('data:image'));});

test('continue plan includes automatic text reveal in its final travel time',()=>{const {s,b}=scene();const a=newActor(source,1);s.actors=[a];s.duration=1;b.text='1234567890';b.textAnimation!.speed=2;b.advance={mode:'auto',seconds:1};a.movement={...newMovement(a),dx:.4,dy:0,duration:6};const next=createTemplate(s,'continue');close(next.actors[0].x,a.x+.4);assert.equal(next.actors[0].movement?.enabled,false);});
test('continue plan does not resurrect an actor whose exit has finished',()=>{const {s}=scene();const a=newActor(source,1),remaining=newActor(source,1);s.actors=[a,remaining];s.duration=6;a.exit={preset:'fade',start:2,duration:1};remaining.exit={preset:'right',start:9,duration:1};const next=createTemplate(s,'continue');assert.equal(next.actors.length,1);assert.equal(next.actors[0].exit,undefined);assert.equal(s.actors.length,2);assert.equal(s.actors[1].exit?.start,9);});
test('late exit and an entrance interrupted by an exit have distinct diagnostics',()=>{const {d,s}=scene();const a=newActor(source,1);s.actors=[a];a.entry={preset:'zoom',delay:0,duration:4};a.exit={preset:'fade',start:1,duration:1};const issues=diagnose(prepareCinematic(d),[source],true);assert.ok(issues.some(i=>i.message.includes('sortie')&&i.message.includes('durée minimale')));assert.ok(issues.some(i=>i.message.includes('avant la fin')));});
test('an exceptionally slow text reveal is diagnosed without rejecting its text',()=>{const {d,b}=scene();b.text='Ce texte apparaît vraiment trop lentement pour être confortable.';b.textAnimation!.speed=.5;const saved=prepareCinematic(d);assert.deepEqual(validationIssues(saved),[]);assert.ok(diagnose(saved,[],false).some(i=>i.message.includes('30 secondes')));assert.equal(saved.shots[0].bubbles[0].text,b.text);});
for(const x of [10,490])for(const y of [15,90])test(`shouting edge glyph at ${x},${y} stays within its text area`,()=>{const p=fitGlyphPose({opacity:1,dx:-40,dy:-10,rotation:12,scale:1.5},x,y,24,32,500,100);const r=p.rotation*Math.PI/180,hx=(Math.abs(Math.cos(r))*24+Math.abs(Math.sin(r))*32)/2*p.scale,hy=(Math.abs(Math.sin(r))*24+Math.abs(Math.cos(r))*32)/2*p.scale;assert.ok(x+p.dx-hx>=-1e-8);assert.ok(x+p.dx+hx<=500+1e-8);assert.ok(y+p.dy-hy>=-1e-8);assert.ok(y+p.dy+hy<=100+1e-8);});
test('resting text is never moved by the expressive bounds guard',()=>{const p={opacity:1,dx:0,dy:0,rotation:0,scale:1};assert.equal(fitGlyphPose(p,1,1,80,70,20,30),p);});
