import {fixturePresentation,PIXEL_PNG} from './presentation-fixture.js';
import test,{type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { seedProject } from '../src/shared/game/seed.js';
import { ensureCampaign, campaignOf, compileCampaign, moveCampaignStep, safeMoviePath, advanceCampaign } from '../src/shared/game/campaign.js';
import { gameIssues, parseGameProject } from '../src/shared/game/validation.js';
import { CampaignSources } from '../src/main/campaignSources.js';
import { planCampaign, publishCampaign } from '../src/main/campaignPublisher.js';
import { newCinematic } from '../src/shared/model.js';
import type { GameProject, CampaignStep } from '../src/shared/game/types.js';
const project=()=>{const p=seedProject();ensureCampaign(p);return p;};
const errors=(p:unknown)=>gameIssues(p).filter(i=>i.severity==='error');
const bad=(mutate:(p:any)=>void)=>{const p=project();mutate(p);assert.ok(errors(p).length>0);};
const steps:CampaignStep[]=[{id:'intro',kind:'cinematic',cinematicId:'f',skippable:true},{id:'level',kind:'level',levelId:'l'},{id:'end',kind:'cinematic',cinematicId:'f',skippable:false}];
test('campaign default references all forty levels without mutating the catalogue',()=>{const p=seedProject(),before=JSON.stringify(p),c=campaignOf(p);assert.equal(c.steps.length,40);assert.equal(JSON.stringify(p),before);assert.ok(c.steps.every(s=>s.kind==='level'));});
test('explicit default sequence is valid and warning-free',()=>assert.deepEqual(gameIssues(project()),[]));
test('publication reorders levels by stable sequence IDs and preserves the authoring library',()=>{const p=project(),first=p.levels[0].id,last=p.levels[39].id;p.campaign!.steps=[p.campaign!.steps[39],p.campaign!.steps[0]];const text=JSON.stringify(p),out=compileCampaign(parseGameProject(p));assert.deepEqual(out.levels.map(l=>l.id),[last,first]);assert.equal(JSON.stringify(p),text);assert.equal(p.levels.length,40);assert.ok(gameIssues(p).some(i=>i.severity==='warning'));});
test('step drag/drop before/after/end is immutable and stable',()=>{const s=structuredClone(steps),before=JSON.stringify(s);assert.deepEqual(moveCampaignStep(s,'end','intro').map(x=>x.id),['end','intro','level']);assert.deepEqual(moveCampaignStep(s,'intro',null).map(x=>x.id),['level','end','intro']);assert.equal(JSON.stringify(s),before);assert.equal(moveCampaignStep(s,'no','intro'),s);assert.equal(moveCampaignStep(s,'intro','no'),s);assert.equal(moveCampaignStep(s,'intro','intro'),s);});
for(const [label,mutate] of [
 ['unknown level',(p:any)=>p.campaign.steps[0].levelId='missing'],
 ['duplicate step',(p:any)=>p.campaign.steps.push(p.campaign.steps[0])],
 ['duplicate level',(p:any)=>p.campaign.steps.push({...p.campaign.steps[0],id:'other'})],
 ['empty sequence',(p:any)=>p.campaign.steps=[]],
 ['no levels',(p:any)=>{p.campaign.cinematics=[{id:'f',title:'Film',file:'a.json',documentId:'d'}];p.campaign.steps=[{id:'s',kind:'cinematic',cinematicId:'f',skippable:true}];}],
 ['missing cinematic',(p:any)=>p.campaign.steps.unshift({id:'s',kind:'cinematic',cinematicId:'missing',skippable:true})],
 ['missing skip flag',(p:any)=>{p.campaign.cinematics=[{id:'f',title:'Film',file:'a.json',documentId:'d'}];p.campaign.steps.unshift({id:'s',kind:'cinematic',cinematicId:'f'});}],
 ['wrong discriminator fields',(p:any)=>p.campaign.steps[0].skippable=true],
 ['missing level reference',(p:any)=>delete p.campaign.steps[0].levelId],
 ['absolute path',(p:any)=>p.campaign.cinematics=[{id:'f',title:'Film',file:'C:/a.json',documentId:'d'}]],
 ['case alias file',(p:any)=>p.campaign.cinematics=[{id:'f',title:'A',file:'intro.json',documentId:'a'},{id:'f2',title:'B',file:'INTRO.json',documentId:'b'}]],
 ['duplicate film id',(p:any)=>p.campaign.cinematics=[{id:'f',title:'A',file:'a.json',documentId:'a'},{id:'f',title:'B',file:'b.json',documentId:'b'}]],
] as [string,(p:any)=>void][])test('campaign rejects '+label,()=>bad(mutate));
for(const file of ['../a.json','/a.json','a//b.json','a/./b.json','C:/a.json','a\\b.json','https://site/a.json','a.json#evil','a.txt','con.json','a /b.json','a\u0000.json'])test('movie path rejects '+JSON.stringify(file),()=>assert.equal(safeMoviePath(file),false));
for(const file of ['intro.json','Europe/Réveil de Lunaria.cinematic.json','Films/été/01.json'])test('movie path accepts '+file,()=>assert.equal(safeMoviePath(file),true));
test('victory only advances the matching level step',()=>{assert.equal(advanceCampaign(steps,1,'level','victory'),2);for(const e of ['defeat','abort','error','finished','skip'] as const)assert.equal(advanceCampaign(steps,1,'level',e),1);assert.equal(advanceCampaign(steps,1,'intro','victory'),1);});
test('optional film can finish or be passed explicitly',()=>{assert.equal(advanceCampaign(steps,0,'intro','finished'),1);assert.equal(advanceCampaign(steps,0,'intro','skip'),1);});
test('mandatory film can only finish',()=>{assert.equal(advanceCampaign(steps,2,'end','skip'),2);assert.equal(advanceCampaign(steps,2,'end','finished'),3);});
test('preview, errors, abort, stale callback and end are read-only',()=>{for(const e of ['error','abort','defeat'] as const)assert.equal(advanceCampaign(steps,0,'intro',e),0);assert.equal(advanceCampaign(steps,0,'intro','finished',true),0);assert.equal(advanceCampaign(steps,1,'intro','finished'),1);assert.equal(advanceCampaign(steps,3,'end','finished'),3);});
async function fixture(fn:(root:string)=>Promise<void>){const root=await fs.mkdtemp(path.join(os.tmpdir(),'lunaria-sequence-'));try{await fn(root);}finally{await fs.rm(root,{force:true,recursive:true});}}
async function symlinkOrSkip(t:TestContext,target:string,link:string,type?:'dir'|'file'|'junction'){try{await fs.symlink(target,link,type);return true;}catch(error){if(process.platform==='win32'&&['EPERM','EACCES'].includes((error as NodeJS.ErrnoException).code??'')){t.skip('Création de liens symboliques non autorisée sur cet hôte Windows.');return false;}throw error;}}
async function setup(root:string){
 const movies=path.join(root,'films'),library=path.join(root,'library'),game=path.join(root,'game'),profile=path.join(root,'profile');
 await fs.mkdir(movies,{recursive:true});await fs.mkdir(library,{recursive:true});await fs.mkdir(path.join(game,'app/controllers'),{recursive:true});await fs.mkdir(path.join(game,'content/design'),{recursive:true});
 await fs.mkdir(path.join(game,'domain/presentation'),{recursive:true});await fs.writeFile(path.join(game,'domain/presentation/animation_registry.gd'),'extends RefCounted');await fs.mkdir(path.join(game,'domain/logic'),{recursive:true});await fs.writeFile(path.join(game,'domain/logic/event_runtime.gd'),'extends RefCounted');
 await fs.writeFile(path.join(game,'project.godot'),'[application]');await fs.writeFile(path.join(game,'app/controllers/campaign_flow.gd'),'extends RefCounted');
 const doc=newCinematic();doc.id='cin_intro';doc.title='Réveil';doc.shots[0].background.asset='library://decor.png';
 await fs.writeFile(path.join(movies,'intro.json'),JSON.stringify(doc));await fs.writeFile(path.join(library,'decor.png'),PIXEL_PNG);
 const p=fixturePresentation(project(),'library://decor.png');p.campaign!.cinematics=[{id:'film_intro',title:doc.title,file:'intro.json',documentId:doc.id}];p.campaign!.steps.unshift({id:'step_intro',kind:'cinematic',cinematicId:'film_intro',skippable:false});p.campaign!.steps.push({id:'step_end',kind:'cinematic',cinematicId:'film_intro',skippable:true});
 const content=path.join(game,'content/design/game_content.json');await fs.writeFile(content,'{"old":true}');
 return {movies,library,game,profile,p,doc,content};
}
test('folder permission is persistent and relative movie identity is checked',()=>fixture(async root=>{const x=await setup(root),sources=new CampaignSources(x.profile);assert.equal(await sources.folder(),'');await sources.select(x.movies);const film=await sources.add(path.join(x.movies,'intro.json'));assert.equal(film.file,'intro.json');assert.equal((await new CampaignSources(x.profile).resolve(film.file,film.documentId)).cinematic.title,'Réveil');await assert.rejects(sources.resolve('../private.json'));await assert.rejects(sources.resolve('intro.json','different'),/correspond/);}));
test('folder resolver refuses selected files and symlinks outside the authorized root',t=>fixture(async root=>{const x=await setup(root),s=new CampaignSources(x.profile);await s.select(x.movies);await fs.writeFile(path.join(root,'external.json'),JSON.stringify(x.doc));await assert.rejects(s.add(path.join(root,'external.json')),/hors/);if(!await symlinkOrSkip(t,path.join(root,'external.json'),path.join(x.movies,'link.json')))return;await assert.rejects(s.resolve('link.json'),/sort/);}));
test('preflight only reads, deduplicates resources, and never changes the author document',()=>fixture(async root=>{const x=await setup(root),before=JSON.stringify(x.p),r=await planCampaign(x.p,x.movies,x.library);assert.equal(r.check.films,1);assert.equal(r.check.assets,1);assert.equal(r.check.steps,42);assert.equal(JSON.stringify(x.p),before);assert.equal(await fs.readFile(x.content,'utf8'),'{"old":true}');assert.ok(r.project.campaign!.cinematics[0].file.startsWith('content/cinematics/studio/'));}));
test('publication is complete, shares repeated images, keeps backup and leaves sources untouched',()=>fixture(async root=>{const x=await setup(root),r=await publishCampaign(x.p,x.game,x.movies,x.library);assert.equal(r.path,x.content);assert.equal(r.films,1);const pub=JSON.parse(await fs.readFile(x.content,'utf8'));assert.deepEqual(errors(pub),[]);assert.equal(await fs.readFile(x.content+'.bak','utf8'),'{"old":true}');assert.ok(await fs.stat(path.join(x.game,pub.campaign.cinematics[0].file)));assert.equal((await fs.readdir(path.join(x.game,'content/cinematics/studio'))).length,1);assert.equal((await fs.readdir(path.join(x.game,'LunariaArtLibrary'))).length,1);assert.equal(x.p.campaign!.cinematics[0].file,'intro.json');assert.equal(JSON.parse(await fs.readFile(path.join(x.movies,'intro.json'),'utf8')).id,'cin_intro');}));
test('republication of identical content is deterministic and non-duplicating',()=>fixture(async root=>{const x=await setup(root);await publishCampaign(x.p,x.game,x.movies,x.library);const first=await fs.readFile(x.content,'utf8');await publishCampaign(x.p,x.game,x.movies,x.library);assert.equal(await fs.readFile(x.content,'utf8'),first);assert.equal((await fs.readdir(path.join(x.game,'content/cinematics/studio'))).length,1);}));
test('changing a film publishes an immutable new blob without rewriting the previous film',()=>fixture(async root=>{const x=await setup(root);await publishCampaign(x.p,x.game,x.movies,x.library);const first=JSON.parse(await fs.readFile(x.content,'utf8')).campaign.cinematics[0].file;x.doc.title='Nouveau titre';await fs.writeFile(path.join(x.movies,'intro.json'),JSON.stringify(x.doc));await publishCampaign(x.p,x.game,x.movies,x.library);const second=JSON.parse(await fs.readFile(x.content,'utf8')).campaign.cinematics[0].file;assert.notEqual(first,second);assert.equal(JSON.parse(await fs.readFile(path.join(x.game,first),'utf8')).title,'Réveil');}));
test('missing film aborts before any active content write',()=>fixture(async root=>{const x=await setup(root);await fs.unlink(path.join(x.movies,'intro.json'));await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/introuvable/);assert.equal(await fs.readFile(x.content,'utf8'),'{"old":true}');}));
test('invalid film aborts without publishing',()=>fixture(async root=>{const x=await setup(root);await fs.writeFile(path.join(x.movies,'intro.json'),'{}');await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library));assert.equal(await fs.readFile(x.content,'utf8'),'{"old":true}');}));
test('missing asset aborts before writes',()=>fixture(async root=>{const x=await setup(root);await fs.unlink(path.join(x.library,'decor.png'));await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/Ressource/);assert.equal(await fs.readFile(x.content,'utf8'),'{"old":true}');}));
test('different existing image is never overwritten',()=>fixture(async root=>{const x=await setup(root);await fs.mkdir(path.join(x.game,'LunariaArtLibrary'));await fs.writeFile(path.join(x.game,'LunariaArtLibrary/decor.png'),'existing image');await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/Conflit/);assert.equal(await fs.readFile(x.content,'utf8'),'{"old":true}');assert.equal(await fs.readFile(path.join(x.game,'LunariaArtLibrary/decor.png'),'utf8'),'existing image');}));
test('symlinked source asset escaping library is refused',t=>fixture(async root=>{const x=await setup(root);await fs.unlink(path.join(x.library,'decor.png'));await fs.writeFile(path.join(root,'private.png'),'secret');if(!await symlinkOrSkip(t,path.join(root,'private.png'),path.join(x.library,'decor.png')))return;await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/Ressource/);}));
test('symlinked target folder is refused even if it is internal',t=>fixture(async root=>{const x=await setup(root);await fs.mkdir(path.join(x.game,'other'));if(!await symlinkOrSkip(t,path.join(x.game,'other'),path.join(x.game,'LunariaArtLibrary'),'dir'))return;await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/non régulière/);assert.equal(await fs.readFile(x.content,'utf8'),'{"old":true}');}));
test('publication rejects old engine and existing publication lock',()=>fixture(async root=>{const x=await setup(root);await fs.writeFile(path.join(x.game,'.lunaria-campaign-publish.lock'),'other publisher');await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/publication/);await fs.unlink(path.join(x.game,'.lunaria-campaign-publish.lock'));await fs.unlink(path.join(x.game,'app/controllers/campaign_flow.gd'));await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.library),/V1.10/);}));
test('level-only campaign needs no movie folder but still publishes its presentation library',()=>fixture(async root=>{const x=await setup(root);const p=fixturePresentation(project(),'library://decor.png');const r=await publishCampaign(p,x.game,'',x.library);assert.equal(r.films,0);assert.equal(r.assets,1);assert.equal(r.levels,40);}));

test('two source files containing the same cinematic share a catalog entry and preserve distinct steps',()=>fixture(async root=>{const x=await setup(root);await fs.copyFile(path.join(x.movies,'intro.json'),path.join(x.movies,'copy.json'));x.p.campaign!.cinematics.push({id:'film_copy',title:'Copie',file:'copy.json',documentId:x.doc.id});x.p.campaign!.steps.push({id:'step_copy',kind:'cinematic',cinematicId:'film_copy',skippable:false});const r=await planCampaign(x.p,x.movies,x.library);assert.equal(r.check.films,1);assert.equal(r.check.steps,43);assert.equal(r.project.campaign!.steps.at(-1)!.kind,'cinematic');assert.equal((r.project.campaign!.steps.at(-1) as any).cinematicId,'film_intro');assert.equal(x.p.campaign!.cinematics.length,2);assert.equal(r.check.assets,1);}));
