import {fixturePresentation,PIXEL_PNG} from './presentation-fixture.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {seedProject} from '../src/shared/game/seed.js';
import {gameIssues,parseGameProject,parseGameDraft} from '../src/shared/game/validation.js';
import {combatReferences,deleteCombatItem,newAbility,newEffect,newProjectile,effectAmount,abilityInterval,abilityRange,EFFECT_KINDS} from '../src/shared/game/combat.js';
import {ensureCombat} from '../src/shared/game/combatDefaults.js';
import {previewAbility} from '../src/shared/game/combatPreview.js';
import {compileCampaign,ensureCampaign} from '../src/shared/game/campaign.js';
import {GameDocuments} from '../src/main/gameDocuments.js';
import {publishCampaign} from '../src/main/campaignPublisher.js';
import type {GameProject} from '../src/shared/game/types.js';
const valid=()=>{const p=seedProject();ensureCampaign(p);return p;};
const errors=(p:unknown)=>gameIssues(p).filter(i=>i.severity==='error');
const alter=(edit:(p:GameProject)=>void)=>{const p=valid();edit(p);return p;};
test('V1.10 seeds 28 plants, 13 enemies and three valid global catalogs',()=>{const p=valid();assert.equal(p.schemaVersion,4);assert.equal(p.balance.plants.length,28);assert.equal(p.balance.enemies.length,13);assert.equal(errors(p).length,0);assert.equal(p.combat!.abilities.length,46);});
test('every species references actual global abilities (not copied records)',()=>{const p=valid();for(const x of [...p.balance.plants,...p.balance.enemies]){assert.ok(x.ability_ids!.length);for(const id of x.ability_ids!)assert.ok(p.combat!.abilities.some(a=>a.id===id));}});
test('one global edit remains one definition across all campaign levels',()=>{const p=valid();p.combat!.effects[0].amount=1.5;const compiled=compileCampaign(p);assert.equal(compiled.combat!.effects[0].amount,1.5);for(const l of compiled.levels){assert.ok(!('combat' in l));assert.ok(!('ability_ids' in l));}});
test('ensureCombat is idempotent and never resets calibrated definitions',()=>{const p=valid();p.combat!.effects[0].amount=2;const before=JSON.stringify(p);ensureCombat(p);assert.equal(JSON.stringify(p),before);});
test('V1.7 authored projects are explicitly imported, without mutating their source',()=>{const old=valid();old.schemaVersion=1;delete old.presentation;delete old.combat;delete old.logic;for(const x of [...old.balance.plants,...old.balance.enemies])delete x.behaviorId;for(const l of old.levels)delete l.events;for(const x of [...old.balance.plants,...old.balance.enemies])delete x.ability_ids;const before=JSON.stringify(old);const p=parseGameProject(old);assert.equal(p.schemaVersion,4);assert.ok(p.combat);assert.equal(JSON.stringify(old),before);});
const invalids:[string,(p:GameProject)=>void][]=[
 ['missing catalog',p=>{delete p.combat;}],['missing species assignments',p=>{delete p.balance.plants[0].ability_ids;}],
 ['unknown assigned ability',p=>{p.balance.enemies[0].ability_ids=['missing'];}],['duplicate assigned ability',p=>{p.balance.plants[0].ability_ids!.push(p.balance.plants[0].ability_ids![0]);}],
 ['ability id collision with species',p=>{p.combat!.abilities[0].id=p.balance.plants[0].id;}],['cross catalog ID collision',p=>{p.combat!.effects[0].id=p.combat!.projectiles[0].id;}],
 ['unknown effect',p=>{p.combat!.abilities[0].effects=['missing'];}],['duplicate effect',p=>{p.combat!.abilities[0].effects=['fx_attack','fx_attack'];}],['empty payload',p=>{p.combat!.abilities[0].effects=[];}],
 ['missing projectile',p=>{p.combat!.abilities[0].projectileId='missing';}],['projectile used to heal allies',p=>{p.combat!.abilities[0].target='ally';}],['projectile all targets',p=>{p.combat!.abilities[0].selection='all';}],
 ['instant with leftover projectile',p=>{p.combat!.abilities[0].delivery='instant';}],['damage on own team',p=>{Object.assign(p.combat!.abilities[0],{target:'self',delivery:'instant',projectileId:''});}],['healing hostile',p=>{p.combat!.abilities[0].effects=['fx_heal'];}],
 ['wounded enemy priority',p=>{p.combat!.abilities[0].priority='wounded';}],['invalid percentage',p=>{p.combat!.effects.find(e=>e.kind==='slow')!.amount=1;}],['percent from attack stat',p=>{p.combat!.effects.find(e=>e.kind==='slow')!.valueSource='attack';}],
 ['oversized damage multiplier',p=>{p.combat!.effects[0].amount=11;}],['empty period',p=>{p.combat!.effects.find(e=>e.kind==='poison')!.tickInterval=0;}],['period after expiry',p=>{p.combat!.effects.find(e=>e.kind==='poison')!.tickInterval=20;}],
 ['root with magnitude',p=>{p.combat!.effects.find(e=>e.kind==='root')!.amount=2;}],['fractional seeds',p=>{p.combat!.effects.find(e=>e.kind==='reward_mark')!.amount=2.3;}],['negative projectile speed',p=>{p.combat!.projectiles[0].speed=-1;}],['zero projectile contact budget',p=>{p.combat!.projectiles[0].maxHits=0;}],
 ['too many contacts',p=>{p.combat!.projectiles[0].maxHits=17;}],['invalid color',p=>{p.combat!.projectiles[0].color='url(x)';}],['NaN cooldown',p=>{p.combat!.abilities[0].cooldown=NaN;}],['infinite effect damage',p=>{p.combat!.effects[0].amount=Infinity;}],['executable script field',p=>{(p.combat!.abilities[0] as any).script='eval(x)';}],
 ['per-level abilities',p=>{(p.levels[0] as any).combat=p.combat;}],['per-level damage override',p=>{(p.levels[0] as any).damage=12;}],['more than eight abilities',p=>{p.balance.plants[0].ability_ids=p.combat!.abilities.slice(0,9).map(a=>a.id);}],['type 1 with v2 payload',p=>{p.schemaVersion=1;}]
];
for(const [name,edit] of invalids)test('invalid combat contract: '+name,()=>assert.ok(errors(alter(edit)).length));
for(const kind of EFFECT_KINDS)test('new '+kind+' effect has structurally valid defaults',()=>{const p=valid();p.combat!.effects.push(newEffect(kind));assert.equal(errors(p).length,0);});
test('a newly created ability can reference a shared effect',()=>{const p=valid();p.combat!.abilities.push(newAbility('fx_attack'));p.combat!.projectiles.push(newProjectile());assert.equal(errors(p).length,0);});
test('references report all source species for contact attack',()=>assert.equal(combatReferences(valid(),'abilities','ab_enemy_contact').length,13));
test('referenced effect cannot be deleted and project is unchanged',()=>{const p=valid(),before=JSON.stringify(p);assert.throws(()=>deleteCombatItem(p,'effects','fx_attack'),/utilisé/);assert.equal(JSON.stringify(p),before);});
test('unused catalog entries can be deleted without disturbing assignments',()=>{const p=valid(),unused=newEffect();p.combat!.effects.push(unused);deleteCombatItem(p,'effects',unused.id);assert.ok(!p.combat!.effects.some(e=>e.id===unused.id));assert.equal(errors(p).length,0);});
test('referenced projectile deletion is refused',()=>assert.throws(()=>deleteCombatItem(valid(),'projectiles','proj_seed')));
test('last unused projectile cannot be deleted',()=>{const p=valid();p.combat!.abilities=p.combat!.abilities.map(a=>({...a,delivery:'instant',projectileId:''}));p.combat!.projectiles=[p.combat!.projectiles[0]];assert.throws(()=>deleteCombatItem(p,'projectiles','proj_seed'),/moins/);});
test('effect scaling fixed, attack and strength uses a single global definition',()=>{const fx=newEffect();assert.equal(effectAmount({...fx,amount:8},{attack:12,strength:2}),8);assert.equal(effectAmount({...fx,valueSource:'attack',amount:2},{attack:12,strength:2}),24);assert.equal(effectAmount({...fx,valueSource:'strength',amount:7},{attack:12,strength:2}),14);});
test('outgoing power modifies damage, not healing or percentages',()=>{const stats={attack:10,strength:1};assert.equal(effectAmount({...newEffect('damage'),amount:10},stats,2),20);assert.equal(effectAmount({...newEffect('heal'),amount:10},stats,2),10);assert.equal(effectAmount(newEffect('slow'),stats,2),.2);});
test('ability cadence and range can independently use source stats or fixed values',()=>{const a=newAbility('fx_attack');assert.equal(abilityInterval(a,{rate:1.7}),1.7);assert.equal(abilityInterval({...a,cooldownSource:'fixed',cooldown:3},{rate:1.7}),3);assert.equal(abilityRange(a,{range:9}),9);assert.equal(abilityRange({...a,rangeSource:'fixed',range:2},{range:9}),2);});
test('single-use damage probe uses target global protection',()=>{const p=valid();const a=newAbility('fx_attack');p.balance.enemies[0].armor=.5;p.balance.enemies[0].resistances.physical=.2;p.balance.plants[0].damage=100;p.balance.enemies[0].hp=1000;const result=previewAbility(p,a,'radish','litterer');assert.equal(result.rows[0].raw,100);assert.equal(result.rows[0].effective,40);assert.equal(result.remainingHp,960);});
test('probe preserves ordered armor break before physical damage',()=>{const p=valid();const a={...newAbility('fx_attack'),effects:['fx_armor_break','fx_attack']};p.balance.enemies[0].armor=.5;p.balance.plants[0].damage=40;const result=previewAbility(p,a,'radish','litterer');assert.equal(result.rows[0].effective,40);});
test('periodic probe starts after interval, respects duration and death',()=>{const p=valid();const a={...newAbility('fx_poison'),effects:['fx_poison']};p.balance.enemies[0].hp=1000;const result=previewAbility(p,a,'radish','litterer');assert.deepEqual(result.rows.map(x=>x.at),[1,2,3]);assert.equal(result.rows.length,3);});
test('unfinished names recover but cannot publish',()=>{const p=valid();p.combat!.abilities[0].name='';assert.doesNotThrow(()=>parseGameDraft(p));assert.throws(()=>parseGameProject(p));});
test('missing v2 draft catalog is refused, never silently replaced',()=>{const p=valid();delete p.combat;assert.throws(()=>parseGameDraft(p));});
async function fixture(fn:(root:string)=>Promise<void>){const root=await mkdtemp(path.join(tmpdir(),'lunaria-combat-'));try{await fn(root);}finally{await rm(root,{recursive:true,force:true});}}
test('new catalog round-trips through real Node file operations and recents',()=>fixture(async root=>{const d=new GameDocuments(path.join(root,'profile'));const p=valid();p.combat!.effects[0].amount=2;const file=path.join(root,'design.game.json');const result=await d.save(p,'',file);const reopened=await d.open(file);assert.deepEqual(reopened.project,p);assert.equal((await d.bootstrap()).recent[0].path,file);assert.ok(result.token);await d.recover(p);assert.deepEqual((await d.bootstrap()).recovery,p);}));
test('publication rejects a dangling ability without writing the content',()=>fixture(async root=>{for(const folder of ['app/controllers','domain/logic','domain/presentation','content/design','LunariaArtLibrary'])await mkdir(path.join(root,folder),{recursive:true});for(const f of ['project.godot','app/controllers/campaign_flow.gd','domain/logic/event_runtime.gd','domain/presentation/animation_registry.gd'])await writeFile(path.join(root,f),'marker');await writeFile(path.join(root,'content/design/game_content.json'),'original');const p=valid();p.balance.plants[0].ability_ids=['unknown'];await assert.rejects(publishCampaign(p,root,'',''));assert.equal(await readFile(path.join(root,'content/design/game_content.json'),'utf8'),'original');}));
test('a global capability publication includes its presentation library even without movies',()=>fixture(async root=>{for(const folder of ['app/controllers','domain/logic','domain/presentation','content/design','LunariaArtLibrary'])await mkdir(path.join(root,folder),{recursive:true});for(const f of ['project.godot','app/controllers/campaign_flow.gd','domain/logic/event_runtime.gd','domain/presentation/animation_registry.gd'])await writeFile(path.join(root,f),'marker');await writeFile(path.join(root,'content/design/game_content.json'),'{}');await writeFile(path.join(root,'LunariaArtLibrary/pixel.png'),PIXEL_PNG);const p=fixturePresentation(valid(),'library://pixel.png');p.combat!.effects[0].amount=2;const result=await publishCampaign(p,root,'',path.join(root,'LunariaArtLibrary'));const out=JSON.parse(await readFile(result.path,'utf8'));assert.equal(result.assets,1);assert.equal(out.combat.effects[0].amount,2);assert.equal(out.schemaVersion,4);}));
test('temporarily empty effect chain recovers but cannot publish',()=>{const p=valid();p.combat!.abilities[0].effects=[];assert.doesNotThrow(()=>parseGameDraft(p));assert.throws(()=>parseGameProject(p));});
test('starter reward mark precedes damage so fatal first contact still marks the target',()=>{assert.deepEqual(valid().combat!.abilities.find(a=>a.id==='ab_banksia')!.effects,['fx_reward','fx_attack']);});
test('readiness warning follows assigned damage payloads, not just a positive base damage stat',()=>{const p=valid();p.levels[0].allowedPlants=['radish'];p.balance.plants[0].ability_ids=['ab_aloe'];assert.ok(gameIssues(p).some(i=>i.severity==='warning'&&i.message.includes('attaque directe')));});
