import {fixturePresentation,PIXEL_PNG} from './presentation-fixture.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {seedProject} from '../src/shared/game/seed.js';import {ensureCampaign,compileCampaign} from '../src/shared/game/campaign.js';import {ensureLogic} from '../src/shared/game/logicDefaults.js';import {ensureCombat} from '../src/shared/game/combatDefaults.js';
import {gameIssues,parseGameProject,parseGameDraft} from '../src/shared/game/validation.js';import {newBehavior,newPhase,newRule,newCondition,newVariable,newAction,newEvent,conditionsMatch,selectPhase,chooseRule,compare,possibleAbilities,logicReferences,logicFilmIds,allActions,behaviorReferences,applyVariable,initialVariables,type LogicContext,type LogicAction} from '../src/shared/game/logic.js';
import {deleteCombatItem} from '../src/shared/game/combat.js';import {cloneLevel,replaceWaves,type GameProject} from '../src/shared/game/types.js';import {GameDocuments} from '../src/main/gameDocuments.js';import {publishCampaign,planCampaign} from '../src/main/campaignPublisher.js';import {newCinematic} from '../src/shared/model.js';
const valid=()=>{const p=seedProject();ensureCampaign(p);p.logic!.variables=[{...newVariable(),id:'flag',type:'boolean',initial:0,minimum:0,maximum:1},{...newVariable(),id:'count',scope:'campaign',minimum:-100,maximum:100,initial:2}];return p;};
const errors=(p:unknown)=>gameIssues(p).filter(e=>e.severity==='error');
const fixtureEvent=(p:GameProject)=>{const ev=newEvent();p.levels[0].events!.push(ev);return ev;};
const ctx=(patch:Partial<LogicContext>={}):LogicContext=>({health:100,time:10,wave:2,enemies:3,energy:50,variables:{flag:0,count:2},ready:()=>true,target:()=>true,...patch});
test('V1.10 ships valid global logic for all 41 species',()=>{const p=valid();assert.equal(p.schemaVersion,4);assert.equal(p.logic!.behaviors.length,9);assert.deepEqual(errors(p),[]);for(const s of [...p.balance.plants,...p.balance.enemies])assert.ok(behaviorReferences(p,s.behaviorId!).includes(s.name));});
test('global behavior modification is shared, no per-level stat copy',()=>{const p=valid();p.logic!.behaviors.find(b=>b.id==='ai_ground')!.stopToAttack=false;const result=compileCampaign(p);assert.equal(result.logic!.behaviors.filter(b=>b.id==='ai_ground').length,1);assert.ok(result.balance.enemies.filter(e=>e.behaviorId==='ai_ground').length>2);assert.ok(result.levels.every(l=>!('logic' in l)));});
test('initializing current combat and logic is idempotent',()=>{const p=valid();p.logic!.behaviors[0].name='Personnalisé';const before=JSON.stringify(p);ensureCombat(p);ensureLogic(p);assert.equal(JSON.stringify(p),before);});
test('V1.8 authoring import preserves balance and never edits its input',()=>{const p=valid();p.schemaVersion=2;delete p.presentation;delete p.logic;for(const s of [...p.balance.plants,...p.balance.enemies])delete s.behaviorId;for(const l of p.levels)delete l.events;p.combat!.abilities=p.combat!.abilities.filter(a=>!a.id.endsWith('_special'));p.combat!.effects=p.combat!.effects.filter(a=>!a.id.includes('_special'));p.balance.enemies[0].hp=987;const before=JSON.stringify(p),up=parseGameProject(p);assert.equal(up.schemaVersion,4);assert.equal(up.balance.enemies[0].hp,987);assert.equal(JSON.stringify(p),before);assert.equal(up.logic!.behaviors.length,9);});
const invalids:[string,(p:GameProject)=>void][]=[
 ['missing logic',p=>{delete p.logic;}],['missing behavior assignment',p=>{delete p.balance.plants[0].behaviorId;}],['wrong team',p=>{p.balance.plants[0].behaviorId='ai_ground';}],['unknown behavior',p=>{p.balance.enemies[0].behaviorId='missing';}],
 ['duplicate behavior',p=>p.logic!.behaviors.push(structuredClone(p.logic!.behaviors[0]))],['cross catalog id',p=>{p.logic!.variables[0].id=p.balance.plants[0].id;}],['missing first phase',p=>{p.logic!.behaviors[0].phases=[];}],['first threshold not 100',p=>{p.logic!.behaviors[0].phases[0].healthBelow=99;}],['increasing phases',p=>{p.logic!.behaviors[3].phases[2].healthBelow=90;}],['duplicate phase id',p=>{p.logic!.behaviors[3].phases[1].id=p.logic!.behaviors[3].phases[0].id;}],['unknown phase ability',p=>{p.logic!.behaviors[0].phases[0].abilityIds=['missing'];}],['duplicate phase ability',p=>{p.logic!.behaviors[0].phases[0].abilityIds=['ab_enemy_contact','ab_enemy_contact'];}],['negative speed',p=>{p.logic!.behaviors[0].phases[0].speedFactor=-1;}],['zero cadence',p=>{p.logic!.behaviors[0].phases[0].attackFactor=0;}],['excess phases',p=>{p.logic!.behaviors[0].phases=Array.from({length:9},(_,i)=>newPhase(i));}],
 ['plant moving by fallback',p=>{p.logic!.behaviors[0].fallback='advance';}],['plant moving by rule',p=>{p.logic!.behaviors[0].rules=[{...newRule(),action:'retreat'}];}],['unknown rule ability',p=>{p.logic!.behaviors[1].rules=[{...newRule(),abilityId:'missing'}];}],['unassigned rule ability',p=>{p.logic!.behaviors[1].rules=[{...newRule(),abilityId:'ab_basic_shot'}];}],['ability leftover on movement',p=>{p.logic!.behaviors[1].rules=[{...newRule(),action:'hold',abilityId:'ab_enemy_contact'}];}],['unknown condition variable',p=>{p.logic!.behaviors[1].rules=[{...newRule(),conditions:[{...newCondition('variable'),ref:'missing'}]}];}],['boolean condition not boolean',p=>{p.logic!.behaviors[1].rules=[{...newRule(),conditions:[{...newCondition('ready'),value:3}]}];}],['health condition too large',p=>{p.logic!.behaviors[1].rules=[{...newRule(),conditions:[{...newCondition('health'),value:101}]}];}],['code in rule',p=>{(p.logic!.behaviors[0] as any).script='eval()';}],
 ['boolean initial not boolean',p=>{p.logic!.variables[0].initial=.2;}],['boolean wrong limits',p=>{p.logic!.variables[0].maximum=2;}],['variable reversed limits',p=>{p.logic!.variables[1].minimum=200;}],['variable invalid initial',p=>{p.logic!.variables[1].initial=200;}],['duplicate variable',p=>{p.logic!.variables.push(structuredClone(p.logic!.variables[0]));}],['non finite variable',p=>{p.logic!.variables[1].initial=NaN;}],
 ['missing events',p=>{delete p.levels[0].events;}],['duplicate event',p=>{const e=fixtureEvent(p);p.levels[1].events=[structuredClone(e)];}],['impossible wave',p=>{fixtureEvent(p).trigger={kind:'wave_start',value:100,ref:''};}],['fractional wave',p=>{fixtureEvent(p).trigger={kind:'wave_end',value:1.2,ref:''};}],['actor-only level condition',p=>{fixtureEvent(p).conditions=[newCondition('health')];}],['health allied trigger',p=>{fixtureEvent(p).trigger={kind:'health',value:50,ref:'radish'};}],['zero interval',p=>{fixtureEvent(p).trigger={kind:'interval',value:0,ref:''};}],['unknown event ability',p=>{fixtureEvent(p).trigger={kind:'ability_used',value:0,ref:'missing'};}],['unknown trigger species',p=>{fixtureEvent(p).trigger={kind:'death',value:0,ref:'missing'};}],['unknown trigger variable',p=>{fixtureEvent(p).trigger={kind:'variable',value:0,ref:'missing'};}],['fractional enemies',p=>{fixtureEvent(p).trigger={kind:'enemies',value:.2,ref:''};}],['negative timer',p=>{fixtureEvent(p).trigger={kind:'time',value:-1,ref:''};}],['no actions',p=>{fixtureEvent(p).actions=[];}],['no repetition cap',p=>{fixtureEvent(p).maxExecutions=0;}],
 ['self level action',p=>{fixtureEvent(p).actions=[{type:'movement',delay:0,target:'self',speciesId:'',speedFactor:1,attackFactor:1,duration:3}];}],['unknown film',p=>{fixtureEvent(p).actions=[{type:'cinematic',delay:0,cinematicId:'missing',skippable:true}];}],['missing action field',p=>{fixtureEvent(p).actions=[{type:'spawn',delay:0,enemyId:'litterer',count:2,lane:1}];}],['extra field',p=>{fixtureEvent(p).actions=[{type:'message',delay:0,text:'Hello',amount:3}];}],['unknown spawn',p=>{fixtureEvent(p).actions=[{type:'spawn',delay:0,enemyId:'missing',count:2,lane:1,interval:1}];}],['out of lane',p=>{fixtureEvent(p).actions=[{type:'spawn',delay:0,enemyId:'litterer',count:2,lane:5,interval:1}];}],['spawn overflow',p=>{fixtureEvent(p).actions=[{type:'spawn',delay:0,enemyId:'litterer',count:65,lane:1,interval:1}];}],['boolean add',p=>{fixtureEvent(p).actions=[{type:'add_variable',delay:0,variableId:'flag',value:1}];}],['boolean assign fraction',p=>{fixtureEvent(p).actions=[{type:'set_variable',delay:0,variableId:'flag',value:.5}];}],['unknown variable action',p=>{fixtureEvent(p).actions=[{type:'set_variable',delay:0,variableId:'missing',value:1}];}],['value beyond range',p=>{fixtureEvent(p).actions=[{type:'set_variable',delay:0,variableId:'count',value:200}];}],['non attributed request',p=>{fixtureEvent(p).actions=[{type:'use_ability',delay:0,target:'enemies',speciesId:'litterer',abilityId:p.balance.plants[0].ability_ids![0]}];}],['unknown effect',p=>{fixtureEvent(p).actions=[{type:'apply_effect',delay:0,target:'enemies',speciesId:'',effectId:'missing'}];}],['wrong target species',p=>{fixtureEvent(p).actions=[{type:'movement',delay:0,target:'plants',speciesId:'litterer',speedFactor:1,attackFactor:1,duration:3}];}],['infinite duration',p=>{fixtureEvent(p).actions=[{type:'shake',delay:0,amount:3,duration:Infinity}];}],['too long sequence',p=>{fixtureEvent(p).actions=Array.from({length:32},()=>({type:'message',text:'Wait',delay:120}));}],['executable event field',p=>{(fixtureEvent(p) as any).eval='code';}]
];for(const [name,edit] of invalids)test('logic contract rejects '+name,()=>{const p=valid();edit(p);assert.ok(errors(p).length,name);});
test('temporarily empty text recovers but cannot publish',()=>{const p=valid();fixtureEvent(p).actions=[{type:'message',delay:0,text:''}];assert.doesNotThrow(()=>parseGameDraft(p));assert.throws(()=>parseGameProject(p));});
test('incomplete draft never invents a missing current logic catalog',()=>{const p=valid();delete p.logic;assert.throws(()=>parseGameDraft(p));});
test('negative variable thresholds are allowed, negative times are not',()=>{const p=valid();fixtureEvent(p).trigger={kind:'variable',value:-50,ref:'count'};assert.equal(errors(p).length,0);});
test('trigger diagnostics carry their level for editor navigation',()=>{const p=valid();fixtureEvent(p).trigger={kind:'wave_start',value:999,ref:''};assert.ok(errors(p).some(i=>i.levelId===p.levels[0].id));});
for(const [op,a,b,want] of [['eq',3,3,true],['eq',3,4,false],['ne',3,4,true],['lt',2,3,true],['lte',3,3,true],['gt',4,3,true],['gte',3,3,true]] as const)test('comparison '+op+' '+a+'/'+b,()=>assert.equal(compare(a,op,b),want));
test('conditions are conjunctions with safe absent references',()=>{const cs=[{...newCondition('health'),value:40},{...newCondition('variable'),ref:'count',value:2}];assert.equal(conditionsMatch(cs,ctx({health:30})),true);assert.equal(conditionsMatch(cs,ctx({health:50})),false);assert.equal(conditionsMatch([{...newCondition('variable'),ref:'missing'}],ctx()),false);assert.equal(conditionsMatch([],ctx()),true);});
test('health phase boundaries are inclusive, monotone after healing',()=>{const b=valid().logic!.behaviors[3];assert.equal(selectPhase(b,100),0);assert.equal(selectPhase(b,66),1);assert.equal(selectPhase(b,33),2);assert.equal(selectPhase(b,10),2);assert.equal(selectPhase(b,90,2),2);});
test('priority uses only first executable rule, fallback is explicit',()=>{const b=newBehavior();b.mode='priority';b.rules=[{...newRule(),id:'flee',conditions:[newCondition('health')],action:'retreat'},{...newRule(),id:'attack'}];assert.equal(chooseRule(b,ctx({health:20}),['contact']).ruleId,'flee');assert.deepEqual(chooseRule(b,ctx(),['contact']).abilities,['contact']);assert.equal(chooseRule(b,ctx({ready:()=>false}),['contact']).movement,'advance');assert.equal(chooseRule(b,ctx({target:()=>false}),['contact']).ruleId,'');});
test('support abilities do not immobilize an advancing enemy in preview',()=>{const b=newBehavior();assert.equal(chooseRule(b,ctx({hostile:()=>false}),['heal']).movement,'advance');assert.equal(chooseRule(b,ctx(),['contact']).movement,'hold');});
test('phase ability pool deduplicates and includes inactive phase capabilities for saved timers',()=>{const p=valid(),s=p.balance.enemies.find(e=>e.id==='collector')!;const pool=possibleAbilities(p,s);assert.ok(pool.includes('ab_collector_special'));assert.equal(new Set(pool).size,pool.length);});
test('ordered rule preview never executes an unassigned requested ability',()=>{const b=newBehavior();b.mode='priority';b.rules=[{...newRule(),abilityId:'not-assigned'},newRule()];assert.deepEqual(chooseRule(b,ctx(),['valid']).abilities,['valid']);});
test('variable application is bounded and level/campaign defaults are disjoint',()=>{const p=valid(),v=p.logic!.variables[1];assert.equal(applyVariable(v,99,50,true),100);assert.equal(applyVariable(v,0,-500),-100);assert.deepEqual(initialVariables(p,'level'),{flag:0});assert.deepEqual(initialVariables(p,'campaign'),{count:2});});
test('deletion protections include rules, phase effects and event conditions',()=>{const p=valid(),b=p.logic!.behaviors[1];b.phases[0].onEnter=[{type:'apply_effect',delay:0,target:'self',speciesId:'',effectId:'fx_poison'}];assert.ok(logicReferences(p,'effects','fx_poison').includes(b.name));assert.throws(()=>deleteCombatItem(p,'effects','fx_poison'));fixtureEvent(p).conditions=[{...newCondition('variable'),ref:'count'}];assert.ok(logicReferences(p,'variables','count').length);});
test('duplicating a level generates fresh event IDs and leaves its references alone',()=>{const p=valid(),e=fixtureEvent(p);const clone=cloneLevel(p.levels[0]);assert.notEqual(clone.events![0].id,e.id);assert.deepEqual(clone.events![0].actions,e.actions);});
test('wave events stay attached to their wave on insertion and are disabled on deletion',()=>{const p=valid(),l=p.levels[0],e=fixtureEvent(p);e.trigger={kind:'wave_start',value:2,ref:''};const inserted=replaceWaves(l,[{id:'extra',groups:[]},...l.waves]);assert.equal(inserted.events![0].trigger.value,3);const removed=replaceWaves(l,l.waves.filter((_,i)=>i!==1));assert.equal(removed.events![0].enabled,false);assert.equal(l.events![0].enabled,true);});
async function withFiles(fn:(root:string)=>Promise<void>){const root=await fs.mkdtemp(path.join(os.tmpdir(),'lunaria-logic-'));try{await fn(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
async function movieProject(root:string){const p=fixturePresentation(valid(),'library://shared.png');p.campaign!.steps=p.campaign!.steps.slice(0,1);const movies=path.join(root,'movies'),lib=path.join(root,'lib'),game=path.join(root,'game');for(const dir of [movies,lib,path.join(game,'app/controllers'),path.join(game,'domain/logic'),path.join(game,'domain/presentation'),path.join(game,'content/design')])await fs.mkdir(dir,{recursive:true});for(const f of ['project.godot','app/controllers/campaign_flow.gd','domain/logic/event_runtime.gd','domain/presentation/animation_registry.gd'])await fs.writeFile(path.join(game,f),'marker');await fs.writeFile(path.join(game,'content/design/game_content.json'),'{}');const c=newCinematic();c.id='cin_event';c.shots[0].background.asset='library://shared.png';await fs.writeFile(path.join(movies,'scene.json'),JSON.stringify(c));await fs.writeFile(path.join(lib,'shared.png'),PIXEL_PNG);p.campaign!.cinematics=[{id:'event_film',title:'Alerte',documentId:c.id,file:'scene.json'}];fixtureEvent(p).actions=[{type:'cinematic',delay:0,cinematicId:'event_film',skippable:false}];return {p,movies,lib,game,c};}
test('event-only movies are retained and published through real file operations',()=>withFiles(async root=>{const x=await movieProject(root),text=JSON.stringify(x.p),out=await publishCampaign(x.p,x.game,x.movies,x.lib),p=JSON.parse(await fs.readFile(out.path,'utf8'));assert.equal(out.films,1);assert.equal(out.assets,1);assert.equal(p.campaign.steps[0].kind,'level');assert.equal(p.campaign.cinematics.length,1);assert.equal(p.levels[0].events[0].actions[0].cinematicId,'event_film');assert.equal(JSON.stringify(x.p),text);assert.equal(errors(p).length,0);}));
test('phase-only movies are retained even when no level event uses them',()=>withFiles(async root=>{const x=await movieProject(root);x.p.levels[0].events=[];x.p.logic!.behaviors[1].phases[0].onEnter=[{type:'cinematic',delay:0,cinematicId:'event_film',skippable:true}];assert.equal((await planCampaign(x.p,x.movies,x.lib)).check.films,1);assert.deepEqual(logicFilmIds(x.p),['event_film']);}));
test('unpublished level event film is not copied',()=>withFiles(async root=>{const x=await movieProject(root);x.p.levels[1].events=x.p.levels[0].events;x.p.levels[0].events=[];assert.equal((await planCampaign(x.p,'',x.lib)).check.films,0);}));
test('missing event film leaves active game content unchanged',()=>withFiles(async root=>{const x=await movieProject(root);await fs.unlink(path.join(x.movies,'scene.json'));await assert.rejects(publishCampaign(x.p,x.game,x.movies,x.lib));assert.equal(await fs.readFile(path.join(x.game,'content/design/game_content.json'),'utf8'),'{}');}));
test('same movie under two source references rewrites event aliases during deduplication',()=>withFiles(async root=>{const x=await movieProject(root);await fs.copyFile(path.join(x.movies,'scene.json'),path.join(x.movies,'other.json'));x.p.campaign!.cinematics.push({id:'another_film',title:'Même alerte',documentId:x.c.id,file:'other.json'});x.p.logic!.behaviors[1].phases[0].onEnter=[{type:'cinematic',delay:0,cinematicId:'another_film',skippable:true}];const plan=await planCampaign(x.p,x.movies,x.lib);assert.equal(plan.check.films,1);const id=plan.project.campaign!.cinematics[0].id;assert.ok(allActions(plan.project).filter(a=>a.type==='cinematic').every(a=>a.cinematicId===id));assert.equal(errors(plan.project).length,0);}));
test('logic project save and recovery round-trip without reinitializing definitions',()=>withFiles(async root=>{const p=valid();fixtureEvent(p);const d=new GameDocuments(root),file=path.join(root,'level.game.json');await d.save(p,'',file);assert.deepEqual((await d.open(file)).project,p);await d.recover(p);assert.deepEqual((await new GameDocuments(root).bootstrap()).recovery,p);}));
