import test from 'node:test';
import assert from 'node:assert/strict';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {seedProject} from '../src/shared/game/seed.js';
import {ensureCampaign} from '../src/shared/game/campaign.js';
import {parseGameProject,parseGameDraft,gameIssues} from '../src/shared/game/validation.js';
import {newCinematic,newActor,upgradeCinematicFormat} from '../src/shared/model.js';
import {parseCinematic} from '../src/shared/schema.js';
import {createHistory,historyReducer} from '../src/shared/history.js';
import {resolveAnimation,species,duration,frameAt,sample,attachmentPoint,releasePlan,eventCue,crossedMarkers,presentationAssets,animationUsages} from '../src/shared/presentation/runtime.js';
import {presentationIssues,cinematicPresentationIssues} from '../src/shared/presentation/validation.js';
import {filmCues} from '../src/shared/presentation/cinematic.js';
import {GameDocuments} from '../src/main/gameDocuments.js';
import {imageDimensions,validatePresentationRegions} from '../src/main/presentationAssets.js';
import {presentationFilmUsages} from '../src/main/presentationUsages.js';
import {CampaignSources} from '../src/main/campaignSources.js';
import {planCampaign,publishCampaign} from '../src/main/campaignPublisher.js';
import {fixturePresentation,PIXEL_PNG} from './presentation-fixture.js';
import type {GameProject} from '../src/shared/game/types.js';
import type {AnimationDefinition} from '../src/shared/presentation/types.js';
import type {Asset} from '../src/shared/model.js';
const p=()=>seedProject();
const errors=(x:GameProject)=>gameIssues(x).filter(e=>e.severity==='error');
const clip=(x:GameProject,id='radish',slot='attack')=>resolveAnimation(x,species(x,id),slot)!;
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-8,`${a} ≠ ${b}`);
const fixtureAsset:Asset={ref:'library://pixel.png',name:'Personnage',url:'',kind:'character',path:'pixel.png',folder:'',bytes:1,modified:0,thumbnail:''};
function film(x:GameProject){const d=newCinematic();d.presentationCatalog={projectId:x.id,file:'content/design/game_content.json'};const a=newActor(fixtureAsset,1);a.name='Radis';a.animation={mode:'species',animationId:'',speciesId:'radish',slot:'attack',speed:1};d.shots[0].actors.push(a);d.shots[0].duration=5;upgradeCinematicFormat(d);return d;}
async function temp(run:(root:string)=>Promise<void>){const root=await fs.mkdtemp(path.join(os.tmpdir(),'lunaria-presentation-'));try{await run(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
test('presentation v4 has forty-one species, explicit profiles and real data defaults',()=>{const x=p();assert.equal(x.schemaVersion,4);assert.equal(x.balance.plants.length+x.balance.enemies.length,41);assert.deepEqual(errors(x),[]);for(const s of [...x.balance.plants,...x.balance.enemies])assert.ok(s.visual?.sprite.asset.startsWith('library://')&&s.animationProfileId);});
for(const slot of ['idle','move','attack','hit','death','spawn'])test('every species resolves '+slot,()=>{const x=p();for(const s of [...x.balance.plants,...x.balance.enemies])assert.ok(resolveAnimation(x,s,slot),s.id);});
test('optional victory may be explicitly absent without a broken reference',()=>{const x=p(),pr=x.presentation!.profiles.find(q=>q.id===species(x,'radish')!.animationProfileId)!;pr.slots.push({slot:'victory',animationId:''});assert.equal(clip(x,'radish','victory'),undefined);assert.deepEqual(errors(x),[]);});
test('missing custom slot is not silently converted to attack',()=>assert.equal(clip(p(),'radish','missing_slot'),undefined));
test('Radis preserves the original four atlas frames and measured anchor',()=>{const a=clip(p());assert.equal(a.id,'radish_throw');assert.equal(a.frames.length,4);assert.deepEqual(a.frames[0].region,{x:9,y:11,width:629,height:558});near(duration(a),.35);near(a.markers.find(m=>m.type==='release')!.at,.182);assert.ok(a.frames.every(f=>f.anchor&&f.asset===a.frames[0].asset));});
for(const [t,index] of [[0,0],[.034,0],[.035,1],[.181,1],[.182,2],[.267,3],[100,3]])test('atlas frame sampling at '+t,()=>assert.equal(frameAt(clip(p()),t).index,index));
test('loop sampling wraps without duplicating gameplay callbacks',()=>{const a=clip(p());a.loop=true;assert.equal(frameAt(a,duration(a)+.01).index,0);assert.equal(frameAt(a,-1).index,0);});
for(const preset of ['none','breath','sway','bounce','shake','recoil','spin','pulse','fade_in','fade_out'] as const)test('pure local transform '+preset+' is finite and non-mutating',()=>{const a=clip(p());a.kind='combined';a.motion.preset=preset;const before=JSON.stringify(a);const value=sample(a,.123);assert.ok(Object.values(value).every(Number.isFinite));assert.equal(JSON.stringify(a),before);assert.deepEqual(sample(a,.123,true),a.transform);});
test('mirror applies to local launch point, not entity coordinates',()=>{const a=clip(p());a.kind='frames';a.transform={x:5,y:3,rotation:0,scaleX:1,scaleY:1,opacity:1};a.attachments=[{id:'launch',x:.9,y:.2}];const l=attachmentPoint(a,0,'launch',{x:100,y:100},false,{x:.5,y:1}),r=attachmentPoint(a,0,'launch',{x:100,y:100},true,{x:.5,y:1});assert.deepEqual(l,{x:45,y:-77});assert.deepEqual(r,{x:-35,y:-77});});
test('one semantic ability resolves two species-specific clips',()=>{const x=p(),ability=x.combat!.abilities.find(a=>a.id==='ab_basic_shot')!;species(x,'bramble')!.ability_ids=[ability.id];const r=releasePlan(x,species(x,'radish')!,ability,1.4),b=releasePlan(x,species(x,'bramble')!,ability,1.4);assert.equal(r.slot,'attack');assert.equal(b.slot,'attack');assert.notEqual(r.animationId,b.animationId);assert.deepEqual(errors(x),[]);});
test('release marker, fallback and immediate plans are explicit',()=>{const x=p(),a=x.combat!.abilities.find(a=>a.id==='ab_basic_shot')!,s=species(x,'radish')!;near(releasePlan(x,s,a,1.4).delay,.182);clip(x).markers=[];a.presentation!.delay=.07;near(releasePlan(x,s,a,1.4).delay,.07);a.presentation!.release='immediate';near(releasePlan(x,s,a,1.4).delay,0);});
test('short cadence scales both visual duration and release delay',()=>{const x=p(),a=x.combat!.abilities.find(a=>a.id==='ab_basic_shot')!;const plan=releasePlan(x,species(x,'radish')!,a,.175);near(plan.speed,2);near(plan.duration,.175);near(plan.delay,.091);a.presentation!.fitCadence=false;near(releasePlan(x,species(x,'radish')!,a,.175).delay,.182);});
test('forward markers include each boundary once, rewind is presentation-free',()=>{const a=clip(p());a.markers=[{id:'one',type:'release',at:.1,ref:'',attach:'launch'},{id:'two',type:'vfx',at:.2,ref:'fx',attach:'center'}];assert.equal(crossedMarkers(a,0,.1).length,1);assert.equal(crossedMarkers(a,.1,.2).length,1);assert.deepEqual(crossedMarkers(a,.2,.1),[]);assert.equal(crossedMarkers(a,.2,.3).length,0);});
test('film playback collects only sound and VFX, never release',()=>{const x=p(),d=film(x),a=clip(x);a.markers=[{id:'r',type:'release',at:.1,ref:'',attach:'launch'},{id:'s',type:'sound',at:.11,ref:x.presentation!.audio[0].id,attach:'head'},{id:'v',type:'vfx',at:.12,ref:x.presentation!.vfx[0].id,attach:'launch'}];assert.deepEqual(filmCues(x,d.shots[0],0,.3).map(c=>c.type),['sound','vfx']);assert.deepEqual(filmCues(x,d.shots[0],.3,0),[]);assert.deepEqual(filmCues(x,d.shots[0],.3,.3),[]);});
test('film actor delay, speed and exit bound marker playback',()=>{const x=p(),d=film(x),a=clip(x),actor=d.shots[0].actors[0];a.markers=[{id:'v',type:'vfx',at:.2,ref:x.presentation!.vfx[0].id,attach:'head'}];actor.entry.delay=1;actor.animation!.speed=2;assert.equal(filmCues(x,d.shots[0],0,1).length,0);near(filmCues(x,d.shots[0],1,1.2)[0].at,1.1);actor.exit={preset:'fade',start:0,duration:.5};assert.equal(filmCues(x,d.shots[0],1,1.2).length,0);});
test('film references exactly one matching shared catalog',()=>{const x=p(),d=film(x);assert.deepEqual(cinematicPresentationIssues(d,x),[]);d.presentationCatalog!.projectId='foreign';assert.ok(cinematicPresentationIssues(d,x).length);delete d.presentationCatalog;assert.ok(cinematicPresentationIssues(d,x).length);});
test('static film has no implicit presentation dependency',()=>assert.deepEqual(cinematicPresentationIssues(newCinematic(),p()),[]));
for(const [name,mutate] of [
 ['missing animation',(x:GameProject)=>{x.presentation!.profiles[0].slots[0].animationId='absent';}],
 ['empty sequence',(x:GameProject)=>{clip(x).frames=[];}],
 ['negative duration',(x:GameProject)=>{clip(x).frames[0].duration=-1;}],
 ['zero duration',(x:GameProject)=>{clip(x).frames[0].duration=0;}],
 ['marker past end',(x:GameProject)=>{clip(x).markers[0].at=5;}],
 ['duplicate release',(x:GameProject)=>{clip(x).markers.push({...clip(x).markers[0],id:'duplicate'});}],
 ['looping attack',(x:GameProject)=>{clip(x).loop=true;}],
 ['executable marker',(x:GameProject)=>{(clip(x).markers[0] as any).type='execute';(clip(x).markers[0] as any).script='damage()';}],
 ['missing sound',(x:GameProject)=>{clip(x).markers.push({id:'s',type:'sound',at:0,ref:'absent',attach:'center'});}],
 ['missing projectile animation',(x:GameProject)=>{x.combat!.projectiles[0].presentation!.animationId='absent';}],
 ['missing projectile presentation',(x:GameProject)=>{delete x.combat!.projectiles[0].presentation;}],
 ['missing v4 catalog',(x:GameProject)=>{delete x.presentation;}],
 ['unsafe resource',(x:GameProject)=>{clip(x).frames[0].asset='library://../outside.png';}],
] as [string,(x:GameProject)=>void][])test('presentation validation rejects '+name,()=>{const x=p();mutate(x);assert.ok(errors(x).length);assert.throws(()=>parseGameProject(x));});
test('v4 recovery does not silently regenerate a removed catalog',()=>{const x=p();delete x.presentation;assert.throws(()=>parseGameDraft(x));});
test('all optional sounds absent remains valid',()=>{const x=fixturePresentation(p(),'library://pixel.png');assert.deepEqual(errors(x),[]);assert.ok(presentationIssues(x).every(e=>e.severity!=='error'));});
test('one sound and one VFX channel use species then ability then default priorities',()=>{const x=p(),s=species(x,'radish')!,profile=x.presentation!.profiles.find(q=>q.id===s.animationProfileId)!;profile.events=profile.events.filter(e=>e.event!=='release');profile.events.push({event:'release',soundId:'species_sound',vfxId:'',attach:'head'});const value=eventCue(x,s,'release',{soundId:'ability_sound',vfxId:'ability_vfx',attach:'launch'});assert.equal(value.soundId,'species_sound');assert.equal(value.vfxId,'ability_vfx');});
test('shared asset closure contains a repeated atlas once',()=>{const x=p(),refs=presentationAssets(x);assert.equal(refs.length,new Set(refs).size);assert.equal(refs.filter(r=>r===clip(x).frames[0].asset).length,1);assert.ok(animationUsages(x,'animations','radish_throw').length>=1);});
test('catalog edits participate in undo and redo without copying external files',()=>{const x=p(),y=structuredClone(x);clip(y).frames[0].duration=.06;let h=historyReducer(createHistory(x),{type:'commit',value:y});h=historyReducer(h,{type:'undo'});assert.deepEqual(h.present,x);h=historyReducer(h,{type:'redo'});assert.deepEqual(h.present,y);});
test('real JSON save, reopen and crash recovery retain profiles and markers',()=>temp(async root=>{const x=p(),docs=new GameDocuments(path.join(root,'profile'));clip(x).markers[0].at=.19;const saved=await docs.save(x,'',path.join(root,'scene.game.json'));assert.deepEqual((await docs.open(saved.path)).project.presentation,x.presentation);await docs.recover(x);assert.deepEqual((await new GameDocuments(path.join(root,'profile')).bootstrap()).recovery!.presentation,x.presentation);}));
test('PNG header and real region preflight reject out-of-bounds atlas',()=>temp(async root=>{assert.deepEqual(imageDimensions(PIXEL_PNG),{width:1,height:1});assert.throws(()=>imageDimensions(Buffer.from('not an image')));await fs.writeFile(path.join(root,'pixel.png'),PIXEL_PNG);const x=fixturePresentation(p(),'library://pixel.png');await validatePresentationRegions(x,root);clip(x).frames[0].region={x:0,y:0,width:2,height:1};await assert.rejects(validatePresentationRegions(x,root),/hors image/);}));
test('linked unopened cinematic protects directly used clip; unreadable film is reported',()=>temp(async root=>{const x=p();ensureCampaign(x);const d=film(x);d.shots[0].actors[0].animation={mode:'animation',animationId:'radish_throw',speciesId:'radish',slot:'attack',speed:1};await fs.writeFile(path.join(root,'film.json'),JSON.stringify(d));x.campaign!.cinematics=[{id:'film',title:'Atelier',file:'film.json',documentId:d.id}];const sources=new CampaignSources(path.join(root,'profile'));await sources.select(root);let usages=await presentationFilmUsages(x,sources);assert.equal(usages.references.radish_throw.length,1);assert.deepEqual(usages.errors,[]);await fs.unlink(path.join(root,'film.json'));usages=await presentationFilmUsages(x,sources);assert.equal(usages.errors.length,1);}));
test('film serialization preserves the shared animation binding',()=>{const x=p(),d=film(x);assert.deepEqual(parseCinematic(JSON.parse(JSON.stringify(d))).shots[0].actors[0].animation,d.shots[0].actors[0].animation);});
test('publication resolves shared catalog and film closure once with no duplicate image',()=>temp(async root=>{const x=fixturePresentation(p(),'library://pixel.png');ensureCampaign(x);const d=film(x);d.presentationCatalog!.file='authoring/custom.game.json';await fs.writeFile(path.join(root,'pixel.png'),PIXEL_PNG);await fs.writeFile(path.join(root,'film.json'),JSON.stringify(d));x.campaign!.cinematics=[{id:'film',title:'Atelier',file:'film.json',documentId:d.id}];x.campaign!.steps.unshift({id:'intro_presentation',kind:'cinematic',cinematicId:'film',skippable:true});const plan=await planCampaign(x,root,root);assert.equal(plan.check.assets,1);const file=plan.files.find(f=>f.relative.endsWith('.cinematic.json'))!;assert.equal(JSON.parse(file.text!).presentationCatalog.file,'content/design/game_content.json');const target=path.join(root,'game');for(const marker of ['project.godot','app/controllers/campaign_flow.gd','domain/logic/event_runtime.gd','domain/presentation/animation_registry.gd']){await fs.mkdir(path.dirname(path.join(target,marker)),{recursive:true});await fs.writeFile(path.join(target,marker),'fixture');}await fs.mkdir(path.join(target,'content/design'),{recursive:true});await publishCampaign(x,target,root,root);await publishCampaign(x,target,root,root);assert.deepEqual(await fs.readdir(path.join(target,'LunariaArtLibrary')),['pixel.png']);assert.equal((await fs.readdir(path.join(target,'content/cinematics/studio'))).length,1);assert.equal(d.presentationCatalog!.file,'authoring/custom.game.json');}));
