import React,{useState} from 'react';
import type { GameProject } from '../../shared/game/types.js';
import type { AbilityDefinition } from '../../shared/game/combat.js';
import {previewAbility} from '../../shared/game/combatPreview.js';
export function CombatProbe({project,ability}:{project:GameProject;ability:AbilityDefinition}){
 const all=[...project.balance.plants,...project.balance.enemies];const [sourceId,setSource]=useState(all.find(x=>x.ability_ids?.includes(ability.id))?.id??all[0].id);
 const plant=project.balance.plants.some(x=>x.id===sourceId);const targets=ability.target==='self'?all.filter(x=>x.id===sourceId):project.balance[(ability.target==='opponent')===plant?'enemies':'plants'];
 const [chosen,setTarget]=useState('');const target=targets.find(x=>x.id===chosen)??targets[0];const probe=previewAbility(project,ability,sourceId,target.id);
 return <details className="gd-combat-probe"><summary>Aperçu chiffré d’une utilisation</summary><p>Calcul sur une cible initialement à pleine santé. Sans combat, aura, pluie, déplacement ni temps de vol ; ce n’est pas une estimation de victoire.</p><div className="gd-form-grid"><label className="gd-field"><span>Porteur d’essai</span><select aria-label="Porteur d’essai" value={sourceId} onChange={e=>setSource(e.target.value)}>{all.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="gd-field"><span>Cible d’essai</span><select aria-label="Cible d’essai" value={target.id} onChange={e=>setTarget(e.target.value)}>{targets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><p>Cadence : {probe.interval} s · portée : {probe.range} cases · PV restants : {probe.remainingHp.toFixed(1)} / {probe.maxHp}</p><table><thead><tr><th>Après impact</th><th>Résultat</th><th>Brut</th><th>Effectif</th><th>PV restants</th></tr></thead><tbody>{probe.rows.slice(0,40).map((r,i)=><tr key={i}><td>{r.at.toFixed(2)} s</td><td>{r.label}</td><td>{r.raw.toFixed(1)}</td><td>{r.effective.toFixed(1)}</td><td>{r.hp.toFixed(1)}</td></tr>)}</tbody></table>{probe.rows.length>40&&<p>Les 40 premières lignes sont affichées ; le total prend en compte tous les déclenchements.</p>}{probe.notes.map((n,i)=><small key={i}>{n}<br/></small>)}</details>;
}
