import type { Asset } from '../../shared/model.js';
import { ensurePresentation } from '../../shared/presentation/defaults.js';
import type { PresentationSection } from '../../shared/presentation/types.js';
import { PresentationEditor } from '../presentation/PresentationEditor.js';
import { BehaviorEditor } from './BehaviorEditor.js';
import { EventEditor } from './EventEditor.js';
import { VariableEditor } from './VariableEditor.js';
import { ensureLogic } from '../../shared/game/logicDefaults.js';
import { CombatEditor } from './CombatEditor.js';
import { ensureCombat } from '../../shared/game/combatDefaults.js';
import React, { forwardRef, useEffect, useImperativeHandle, useMemo, useReducer, useRef, useState } from 'react';
import { createHistory, historyReducer, type HistoryAction } from '../../shared/history.js';
import { seedProject } from '../../shared/game/seed.js';
import { cloneLevel, CONTINENTS, newId,newLevel, totalEnemies, OBJECTIVES, OBJECTIVE_LABELS, type GameProject, type LevelDefinition, type GameRecent, type GameFile, type GameBuildTarget } from '../../shared/game/types.js';
import { gameIssues, parseGameProject } from '../../shared/game/validation.js';
import { api } from '../browserBridge.js';
import { gameAPI } from './bridge.js';
import { BalanceEditor, Num } from './BalanceEditor.js';
import { WaveEditor } from './WaveEditor.js';
import { CampaignEditor } from './CampaignEditor.js';
import { ensureCampaign } from '../../shared/game/campaign.js';
import type { CampaignFilm } from '../../shared/game/types.js';
import './game.css';
function starter(){const p=seedProject();ensureCombat(p);ensureCampaign(p);ensureLogic(p);return p;}
export interface GameEditorHandle {prepareClose():Promise<boolean>;isBusy():boolean}
interface Props {assets:Asset[];onProject:(p:GameProject)=>void;externalUsages:Record<string,string[]>;active:boolean;onDirty:(dirty:boolean)=>void;onBusy:(busy:boolean)=>void;onOpenFilm:(film:CampaignFilm)=>Promise<void>;onBeforePublish:()=>Promise<boolean>}
export const GameEditor=forwardRef<GameEditorHandle,Props>(function GameEditor({assets,onProject,externalUsages,active,onDirty,onBusy,onOpenFilm,onBeforePublish},ref){
 const [history,dispatch]=useReducer(historyReducer<GameProject>,undefined,()=>createHistory(starter()));
 const project=history.present;
 const [saved,setSaved]=useState(()=>JSON.stringify(project)),[path,setPath]=useState(''),[token,setToken]=useState('');
 const [section,setSection]=useState<'campaign'|'levels'|'plants'|'enemies'|'abilities'|'behaviors'|'variables'|PresentationSection>('campaign'),[levelId,setLevelId]=useState(project.levels[0].id);
 const [combatId,setCombatId]=useState('');
 const [species,setSpecies]=useState('radish'),[detail,setDetail]=useState<'settings'|'waves'|'plants'|'events'>('waves');
 const [query,setQuery]=useState(''),[continent,setContinent]=useState(-1),[busy,setBusy]=useState(false),[booted,setBooted]=useState(false);
 const [message,setMessage]=useState(''),[recovery,setRecovery]=useState<GameProject|null>(null),[recent,setRecent]=useState<GameRecent[]>([]),[showRecent,setShowRecent]=useState(false),[showIssues,setShowIssues]=useState(false);
 const [recoveryStatus,setRecoveryStatus]=useState('');
 const stateRef=useRef(history);stateRef.current=history;const savedRef=useRef(saved);savedRef.current=saved;const running=useRef(false);
 const pathRef=useRef(path),tokenRef=useRef(token);pathRef.current=path;tokenRef.current=token;const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const dirty=JSON.stringify(project)!==saved,issues=useMemo(()=>gameIssues(project),[project]),errors=issues.filter(x=>x.severity==='error');
 const level=project.levels.find(l=>l.id===levelId)??project.levels[0];
 function action(a:HistoryAction<GameProject>){const next=historyReducer(stateRef.current,a);stateRef.current=next;dispatch(a);}
 function change(edit:(p:GameProject)=>void,key='',label='Modifier le projet de jeu',allowBusy=false){
  if(running.current&&!allowBusy)return;const next=structuredClone(stateRef.current.present);edit(next);action({type:'commit',value:next,key,now:Date.now(),label});
 }
 function updateLevel(patch:Partial<LevelDefinition>,key='') {const id=level.id;change(p=>Object.assign(p.levels.find(l=>l.id===id)!,patch),key?`${id}:${key}`:'');}
 function flushInput(){if(document.activeElement instanceof HTMLElement)document.activeElement.blur();}
 function report(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function run(fn:()=>Promise<void>){if(running.current)return;flushInput();running.current=true;setBusy(true);try{await fn();}catch(e){report(e);}finally{running.current=false;setBusy(false);}}
 async function refreshRecent(){try{setRecent((await gameAPI.bootstrap()).recent);}catch(e){report(e);}}
 async function save(as=false):Promise<boolean>{
  clearTimeout(timer.current);const current=stateRef.current.present;parseGameProject(current);
  const result=await gameAPI.save(current,tokenRef.current,as);if(!result)return false;
  savedRef.current=JSON.stringify(result.project);setSaved(savedRef.current);pathRef.current=result.path;setPath(result.path);tokenRef.current=result.token;setToken(result.token);
  await gameAPI.clearRecovery();setRecoveryStatus('Fichier enregistré');setMessage('Projet de niveaux et équilibrage global enregistrés.');await refreshRecent();return true;
 }
 async function canReplace(reason:string):Promise<boolean>{
  flushInput();if(savedRef.current===JSON.stringify(stateRef.current.present))return true;
  const choice=await api.confirmUnsaved(reason);if(choice==='cancel')return false;
  if(choice==='save')return save();return true;
 }
 useImperativeHandle(ref,()=>({isBusy:()=>running.current,prepareClose:async()=>{if(running.current)return false;try{const proceed=await canReplace('Enregistrer le projet de niveaux et son équilibrage avant de quitter ?');if(proceed&&savedRef.current!==JSON.stringify(stateRef.current.present)){clearTimeout(timer.current);await gameAPI.recover(stateRef.current.present);}return proceed;}catch(e){report(e);return false;}}}));
 function apply(project:GameProject,file?:GameFile,modified=false){
  project=structuredClone(project);ensureCampaign(project);
  clearTimeout(timer.current);ensureCombat(project);ensureLogic(project);ensurePresentation(project);action({type:'reset',value:structuredClone(project)});setLevelId(project.levels[0].id);setSpecies(project.balance.plants[0].id);setSection('campaign');setQuery('');setContinent(-1);setDetail('waves');
  const baseline=modified?'':JSON.stringify(project);savedRef.current=baseline;setSaved(baseline);pathRef.current=file?.path??'';setPath(pathRef.current);tokenRef.current=file?.token??'';setToken(tokenRef.current);setShowRecent(false);setRecovery(null);setRecoveryStatus(file?'Fichier ouvert':'');
 }
 const open=(recentPath?:string)=>run(async()=>{if(!await canReplace('Enregistrer avant d’ouvrir un autre projet de niveaux ?'))return;const result=await (recentPath?gameAPI.openRecent(recentPath):gameAPI.open());if(result){apply(result.project,result);await gameAPI.clearRecovery();await refreshRecent();setMessage('Projet ouvert.');}});
 const fresh=(campaign=false)=>run(async()=>{if(!await canReplace('Enregistrer avant de créer un projet de niveaux ?'))return;const next=seedProject();if(!campaign){next.id='nouveau_jeu';next.title='Nouveau projet Lunaria';next.balance=structuredClone(stateRef.current.present.balance);next.combat=structuredClone(stateRef.current.present.combat);next.logic=structuredClone(stateRef.current.present.logic);next.schemaVersion=4;next.presentation=structuredClone(stateRef.current.present.presentation);next.levels=[newLevel(next.balance.plants.map(p=>p.id),next.balance.enemies[0].id)];next.campaign={steps:[{id:newId('step'),kind:'level',levelId:next.levels[0].id}],cinematics:structuredClone(stateRef.current.present.campaign?.cinematics??[])};}apply(next,undefined,true);await gameAPI.clearRecovery();setMessage(campaign?'Les 40 niveaux fournis sont chargés.':'Projet créé avec le catalogue global courant.');});
 const addLevel=()=>{const next=newLevel(project.balance.plants.map(p=>p.id),project.balance.enemies[0].id);next.act=level.act;change(p=>{const i=p.levels.findIndex(l=>l.id===level.id);p.levels.splice(i+1,0,next);},'','Créer un niveau');setLevelId(next.id);setDetail('settings');};
 const duplicate=()=>{const next=cloneLevel(level);change(p=>p.levels.splice(p.levels.findIndex(l=>l.id===level.id)+1,0,next),'','Dupliquer le niveau');setLevelId(next.id);};
 const remove=()=>run(async()=>{if(project.levels.length<2||!await api.confirmDelete(level.title))return;
  // The asynchronous confirmation may finish after a render; edit from the current state.
  const next=structuredClone(stateRef.current.present),i=next.levels.findIndex(l=>l.id===level.id);if(i<0)return;next.levels.splice(i,1);if(next.campaign)next.campaign.steps=next.campaign.steps.filter(s=>s.kind!=='level'||s.levelId!==level.id);action({type:'commit',value:next,label:'Supprimer le niveau'});setLevelId(next.levels[Math.min(i,next.levels.length-1)].id);
 });
 const move=(by:number)=>change(p=>{const i=p.levels.findIndex(l=>l.id===level.id),j=i+by;if(j<0||j>=p.levels.length)return;[p.levels[i],p.levels[j]]=[p.levels[j],p.levels[i]];},'','Réordonner les niveaux');
 const playLevel=()=>void run(async()=>{const id=level.id;if(!await onBeforePublish())return;const result=await gameAPI.playLevel(stateRef.current.present,id);if(result)setMessage(`Lunaria lancé sur « ${result.title} ». Les données du Studio ont été synchronisées. Cette session de test est temporaire et n’écrit pas dans la progression du joueur.`);});
 const buildGame=(target:GameBuildTarget)=>void run(async()=>{if(!await onBeforePublish())return;const label=target==='windows'?'PC':'Android';setMessage(`Build ${label} en cours… La campagne est synchronisée avant l’export.`);const result=await gameAPI.build(stateRef.current.present,target);setMessage(result?`Build ${label} terminé : ${result.artifact}\n${(result.bytes/1048576).toFixed(1)} Mo · SHA-256 ${result.sha256}`:`Build ${label} annulé.`);});
 useEffect(()=>{let live=true;gameAPI.bootstrap().then(r=>{if(live){setRecent(r.recent);setRecovery(r.recovery);}}).catch(report).finally(()=>{if(live)setBooted(true);});return()=>{live=false;clearTimeout(timer.current);};},[]);
 useEffect(()=>{onProject(project);},[project,onProject]);
 useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 useEffect(()=>{onBusy(busy);},[busy,onBusy]);
 useEffect(()=>{clearTimeout(timer.current);if(!dirty||!booted||recovery)return;setRecoveryStatus('Copie en attente…');const value=project;let current=true;
  timer.current=setTimeout(()=>{void gameAPI.recover(value).then(()=>{if(current)setRecoveryStatus('Copie locale à jour');}).catch(e=>{if(current){setRecoveryStatus('Copie locale en erreur');report(e);}});},500);return()=>{current=false;clearTimeout(timer.current);};
 },[project,dirty,booted,recovery]);
 useEffect(()=>{if(!active)return;const key=(e:KeyboardEvent)=>{if(e.defaultPrevented||e.isComposing)return;const cmd=e.ctrlKey||e.metaKey;
  if(cmd&&e.key.toLowerCase()==='s'){e.preventDefault();void run(async()=>{await save(e.shiftKey);});return;}
  if(cmd&&e.key.toLowerCase()==='o'){e.preventDefault();void open();return;}
  if(e.target instanceof Element&&e.target.closest('input,textarea,select,[contenteditable]'))return;
  if(!busy&&cmd&&e.key.toLowerCase()==='z'){e.preventDefault();action({type:e.shiftKey?'redo':'undo'});}else if(!busy&&cmd&&e.key.toLowerCase()==='y'){e.preventDefault();action({type:'redo'});}
 };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 useEffect(()=>{if(!project.levels.some(l=>l.id===levelId))setLevelId(project.levels[0].id);},[project,levelId]);
 const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const visible=project.levels.filter(l=>(continent<0||l.act===continent)&&norm(l.title+' '+l.id+' '+l.location).includes(norm(query)));
 const selectSection=(next:typeof section)=>{if(running.current)return;setSection(next);setSpecies(next==='enemies'?project.balance.enemies[0].id:project.balance.plants[0].id);};
 const openCombatIssue=(path:string)=>{const [,kind,id='']=path.split('.');let attackId=id;if(kind==='effects')attackId=project.combat!.abilities.find(a=>a.effects.includes(id))?.id??'';else if(kind==='projectiles')attackId=project.combat!.abilities.find(a=>a.projectileId===id)?.id??'';setSection('abilities');setCombatId(attackId);};
 return <div className="gd-shell" aria-label="Éditeur de niveaux">
  <header className="gd-toolbar"><div className="gd-project-name"><span className="gd-kicker">PROJET DE JEU</span><input aria-label="Titre du projet de niveaux" maxLength={160} value={project.title} disabled={busy} onChange={e=>change(p=>{p.title=e.target.value;},'title')}/><small title={path}>{path||'Non enregistré · un seul catalogue pour tout le jeu'}{dirty?' · Modifié':''}</small></div>
   <div className="gd-inline"><button disabled={busy||!booted} onClick={()=>void fresh()}>Nouveau</button><button disabled={busy||!booted} onClick={()=>void open()}>Ouvrir</button><button disabled={busy} aria-expanded={showRecent} onClick={()=>setShowRecent(!showRecent)}>Récents</button><button disabled={busy||!history.past.length} onClick={()=>{flushInput();action({type:'undo'});}} title="Annuler · Ctrl+Z">↶</button><button disabled={busy||!history.future.length} onClick={()=>{flushInput();action({type:'redo'});}} title="Rétablir · Ctrl+Y">↷</button><button disabled={busy} onClick={()=>void run(async()=>{await save(true);})}>Enregistrer sous</button><button className="gd-primary" disabled={busy} onClick={()=>void run(async()=>{await save();})}>Enregistrer</button><button className="gd-publish" disabled={busy||errors.length>0} onClick={()=>void run(async()=>{if(!await onBeforePublish())return;const result=await gameAPI.publish(stateRef.current.present);if(result)setMessage('Publié : '+result.path+'\nRelance le jeu pour utiliser ces données.');})}>Publier la campagne</button><button className="gd-build gd-build-pc" disabled={busy||errors.length>0} title="Synchroniser la campagne puis générer build/windows/Lunaria.exe" onClick={()=>buildGame('windows')}>Build PC</button><button className="gd-build gd-build-android" disabled={busy||errors.length>0} title="Synchroniser la campagne puis générer build/android/Lunaria.apk" onClick={()=>buildGame('android')}>Build Android</button></div>
  </header>
  {recovery&&<div className="gd-recovery">Une copie locale non enregistrée est disponible : <b>{recovery.title}</b><button onClick={()=>{apply(recovery,undefined,true);setMessage('Brouillon récupéré. Enregistrer sous choisira sa destination.');}}>Reprendre</button><button onClick={()=>void run(async()=>{await gameAPI.clearRecovery();setRecovery(null);})}>Ignorer</button></div>}
  {showRecent&&<div className="gd-recents"><b>Derniers projets de niveaux</b>{recent.length?recent.map(r=><button disabled={busy} key={r.path} onClick={()=>void open(r.path)}><strong>{r.title}</strong><small>{r.path}</small></button>):<p>Les projets ouverts ou enregistrés apparaîtront ici. Leurs images ne sont jamais copiées.</p>}<button onClick={()=>setShowRecent(false)}>Fermer</button></div>}
  <nav className="gd-sections" aria-label="Sections du mode Niveaux"><button className={section==='campaign'?'active':''} onClick={()=>selectSection('campaign')}>Campagne <small>Ordre de lecture</small></button><button className={section==='levels'?'active':''} onClick={()=>selectSection('levels')}>Niveaux <small>{project.levels.length}</small></button><button className={section==='plants'?'active':''} onClick={()=>selectSection('plants')}>Plantes alliées <small>Équilibrage global</small></button><button className={section==='enemies'?'active':''} onClick={()=>selectSection('enemies')}>Ennemis <small>Équilibrage global</small></button><button className={section==='abilities'?'active':''} onClick={()=>{selectSection('abilities');setCombatId('');}}>Attaque <small>Types & résultats</small></button><button className={section==='behaviors'?'active':''} onClick={()=>{selectSection('behaviors');setCombatId('');}}>Comportements <small>IA & phases de boss</small></button><button className={section==='variables'?'active':''} onClick={()=>selectSection('variables')}>Variables</button><span>Équilibrage global · sans progression</span></nav>
  <details className="lp-navigation" open={['animations','profiles','audio','vfx'].includes(section)||undefined}><summary>Présentation · animations, profils, audio et VFX</summary><div>{(['animations','profiles','audio','vfx'] as const).map(k=><button key={k} className={section===k?'active':''} onClick={()=>{selectSection(k);setCombatId('');}}>{{animations:'Animations',profiles:'Profils d’animation',audio:'Audio',vfx:'VFX'}[k]}</button>)}</div></details>
  <fieldset className="gd-body" disabled={busy}>
  {(section==='animations'||section==='profiles'||section==='audio'||section==='vfx')?<PresentationEditor project={project} section={section} id={combatId} select={setCombatId} assets={assets} externalUsages={externalUsages} change={(edit,key,label)=>change(edit,key,label,true)} report={setMessage} run={run} openAnimation={id=>{setSection('animations');setCombatId(id);}}/>:section==='behaviors'?<BehaviorEditor project={project} id={combatId} select={setCombatId} change={(edit,key,label)=>change(edit,key,label,true)} report={setMessage}/>:section==='variables'?<VariableEditor project={project} change={(edit,key,label)=>change(edit,key,label,true)} report={setMessage}/>:section==='campaign'?<CampaignEditor project={project} change={(edit,key,label)=>change(edit,key,label,true)} run={run} report={setMessage} selectLevel={id=>{setLevelId(id);setSection('levels');}} openFilm={film=>run(()=>onOpenFilm(film))}/>:section==='abilities'?<CombatEditor assets={assets} project={project} id={combatId} select={setCombatId} change={(edit,key,label)=>change(edit,key,label,true)} report={setMessage} run={run}/>:section!=='levels'?<BalanceEditor assets={assets} change={(edit,key,label)=>change(edit,key,label,true)} openAnimation={id=>{setSection('animations');setCombatId(id);}} openProfile={id=>{setSection('profiles');setCombatId(id);}} editBehavior={id=>{setSection('behaviors');setCombatId(id);}} editAbility={id=>{setSection('abilities');setCombatId(id);}} project={project} role={section} id={species} select={setSpecies} update={(id,patch,key)=>change(p=>{const list=section==='plants'?p.balance.plants:p.balance.enemies;Object.assign(list.find(x=>x.id===id)!,patch);},key,'Calibrer le catalogue global')}/>:<>
   <aside className="gd-level-list"><div className="gd-list-controls"><input aria-label="Rechercher un niveau" placeholder="Rechercher un niveau…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrer les niveaux par continent" value={continent} onChange={e=>setContinent(Number(e.target.value))}><option value={-1}>Tous les continents</option>{CONTINENTS.map((c,i)=><option key={c} value={i}>{c}</option>)}</select><button className="gd-primary" disabled={project.levels.length>=200} onClick={addLevel}>+ Créer un niveau</button></div>
    <div className="gd-level-items">{visible.map(l=><button key={l.id} className={level.id===l.id?'selected':''} onClick={()=>setLevelId(l.id)}><span className="gd-level-index">{String(project.levels.indexOf(l)+1).padStart(2,'0')}</span><span><b>{l.title}</b><small>{CONTINENTS[l.act]} · {l.waves.length} vague{l.waves.length>1?'s':''} · {totalEnemies(l)} ennemis</small></span></button>)}{!visible.length&&<p>Aucun niveau ne correspond.</p>}</div>
    <button onClick={()=>void fresh(true)}>Recharger la campagne fournie</button>
   </aside>
   <main className="gd-level-main gd-scroll" key={level.id}>
    <div className="gd-section-heading"><div><div className="gd-kicker">NIVEAU {String(project.levels.indexOf(level)+1).padStart(2,'0')} · {CONTINENTS[level.act]}</div><h1>{level.title}</h1><p>{level.location||'Lieu à définir'} · <strong>{totalEnemies(level)} ennemis</strong> · {level.allowedPlants.length} plantes autorisées</p></div><div className="gd-inline"><button className="gd-play-level" disabled={errors.length>0} title="Synchroniser les données puis ouvrir ce niveau dans Lunaria avec une progression de test séparée" onClick={playLevel}>▶ Jouer ce niveau</button><button aria-label="Monter le niveau" disabled={project.levels.indexOf(level)===0} onClick={()=>move(-1)}>↑</button><button aria-label="Descendre le niveau" disabled={project.levels.indexOf(level)===project.levels.length-1} onClick={()=>move(1)}>↓</button><button disabled={project.levels.length>=200} onClick={duplicate}>Dupliquer</button><button disabled={project.levels.length<=1} onClick={()=>void remove()}>Supprimer</button></div></div>
    <nav className="gd-detail-tabs" aria-label="Édition du niveau">{([['settings','Paramètres'],['waves','Vagues & ennemis'],['plants','Plantes disponibles'],['events','Événements & dialogue']] as const).map(([key,label])=><button key={key} className={detail===key?'active':''} onClick={()=>setDetail(key)}>{label}</button>)}</nav>
    {detail==='settings'&&<><div className="gd-form-grid">
     <label className="gd-field"><span>Nom du niveau</span><input aria-label="Nom du niveau" maxLength={160} value={level.title} onChange={e=>updateLevel({title:e.target.value},'title')}/></label>
     <label className="gd-field"><span>Continent</span><select aria-label="Continent du niveau" value={level.act} onChange={e=>updateLevel({act:Number(e.target.value)})}>{CONTINENTS.map((c,i)=><option key={c} value={i}>{c}</option>)}</select></label>
     <label className="gd-field"><span>Lieu</span><input aria-label="Lieu du niveau" maxLength={200} value={level.location} onChange={e=>updateLevel({location:e.target.value},'location')}/></label>
     <Num label="Graines initiales" value={level.startingEnergy} max={100000} integer change={v=>updateLevel({startingEnergy:v})}/>
     <label className="gd-field"><span>Objectif</span><select aria-label="Objectif du niveau" value={level.objective.type} onChange={e=>updateLevel({objective:{type:e.target.value as LevelDefinition['objective']['type'],target:e.target.value==='rescue'?3:e.target.value==='defend'?0:60}})}>{OBJECTIVES.map(x=><option key={x} value={x}>{OBJECTIVE_LABELS[x]}</option>)}</select></label>
     {!['defend','rescue'].includes(level.objective.type)&&<Num label="Travail à accomplir" value={level.objective.target} max={3600} min={1} integer change={v=>updateLevel({objective:{...level.objective,target:v}})}/>}
    </div><label className="gd-field"><span>Consigne affichée</span><textarea aria-label="Consigne du niveau" rows={2} maxLength={1000} value={level.objectiveText} onChange={e=>updateLevel({objectiveText:e.target.value},'objectiveText')}/></label><label className="gd-field"><span>Conseil</span><textarea rows={2} maxLength={1000} value={level.tip} onChange={e=>updateLevel({tip:e.target.value},'tip')}/></label><p className="gd-callout">Le plateau est toujours composé de 5 allées × 8 cases ordinaires. Aucun obstacle ni bonus de statistiques n’est attaché à ce niveau.</p></>}
    {detail==='waves'&&active&&<WaveEditor level={level} enemies={project.balance.enemies} update={updateLevel}/>}
    {detail==='plants'&&<><div className="gd-section-heading"><div><h2>Choisis les espèces utilisables</h2><p>Le joueur choisit 5 espèces parmi cette sélection (ou toutes si tu en autorises moins de 5). Aucune condition de recrutement ne peut retirer une plante autorisée ici.</p></div><div className="gd-inline"><button onClick={()=>updateLevel({allowedPlants:project.balance.plants.map(p=>p.id)})}>Toutes</button></div></div><div className="gd-plant-picker">{project.balance.plants.map(p=><label key={p.id} className={level.allowedPlants.includes(p.id)?'selected':''}><input type="checkbox" aria-label={`Autoriser ${p.name}`} checked={level.allowedPlants.includes(p.id)} onChange={e=>updateLevel({allowedPlants:e.target.checked?[...level.allowedPlants,p.id]:level.allowedPlants.filter(x=>x!==p.id)})}/><span><b>{p.name}</b><small>{p.role}</small><small>{p.cost} graines · {p.max_hp} PV · {p.damage} dégâts</small></span></label>)}</div><p className="gd-note">Les valeurs sont en lecture seule ici. Pour les modifier partout, ouvre « Plantes alliées — Équilibrage global ».</p></>}
    {detail==='events'&&<><EventEditor project={project} level={level} update={events=>updateLevel({events})} addFilm={()=>void run(async()=>{const film=await gameAPI.addCampaignFilm();if(!film)return;change(p=>{const c=ensureCampaign(p);if(!c.cinematics.some(f=>f.file===film.file))c.cinematics.push(film);},'','Lier un film aux événements',true);setMessage('Film lié au catalogue. Il peut être sélectionné dans les actions.');})}/><section className="gd-story gd-mid-dialogue"><div className="gd-section-heading"><div><h2>Dialogue pendant la mission</h2><p>Facultatif : ces répliques apparaissent au début de la vague choisie. Les cinématiques avant et après le niveau se règlent dans « Campagne ».</p></div><Num label="Vague (0 = aucun dialogue)" value={level.midWave} max={level.waves.length} integer change={v=>updateLevel({midWave:v})}/></div>{level.midDialogue.map((line,i)=><div className="gd-story-line" key={i}><input aria-label={`Locuteur du dialogue ${i+1}`} maxLength={100} value={line.speaker} onChange={e=>{const lines=structuredClone(level.midDialogue);lines[i].speaker=e.target.value;updateLevel({midDialogue:lines},`midDialogue${i}speaker`);}}/><textarea aria-label={`Texte du dialogue ${i+1}`} rows={2} maxLength={8000} value={line.text} onChange={e=>{const lines=structuredClone(level.midDialogue);lines[i].text=e.target.value;updateLevel({midDialogue:lines},`midDialogue${i}text`);}}/><button aria-label={`Supprimer la réplique ${i+1}`} onClick={()=>updateLevel({midDialogue:level.midDialogue.filter((_,n)=>n!==i)})}>×</button></div>)}<button disabled={level.midDialogue.length>=100} onClick={()=>updateLevel({midDialogue:[...level.midDialogue,{speaker:'Narration',text:'Nouvelle réplique.'}]})}>+ Réplique</button></section></>}
   </main>
  </>}
  </fieldset>
  <footer className="gd-footer"><span>{busy?'Opération en cours…':recoveryStatus||'Un catalogue partagé · aucun fichier image dupliqué'}</span><button className={errors.length?'gd-error':''} onClick={()=>setShowIssues(!showIssues)}>{issues.length?`${errors.length} erreur(s) · ${issues.length-errors.length} avertissement(s)`:'✓ Projet valide'}</button></footer>
  {showIssues&&<section className="gd-issues"><div className="gd-section-heading"><h2>Vérifications</h2><button onClick={()=>setShowIssues(false)}>Fermer</button></div>{issues.length?issues.map((i,n)=><button key={n} onClick={()=>{if(i.path.startsWith('presentation.')){const parts=i.path.split('.');setSection((['animations','profiles','audio','vfx'].includes(parts[1])?parts[1]:'animations') as PresentationSection);setCombatId(parts[2]??'');}else if(i.path.startsWith('logic.')){const parts=i.path.split('.');setSection(parts[1] as 'behaviors'|'variables');setCombatId(parts[2]??'');}else if(i.path.startsWith('combat.'))openCombatIssue(i.path);else if(i.path.startsWith('balance.')){const parts=i.path.split('.');setSection(parts[1] as 'plants'|'enemies');setSpecies(parts[2]??'');}else if(i.path.startsWith('campaign'))setSection('campaign');else if(i.levelId){setLevelId(i.levelId);setSection('levels');if(i.path.includes('.events.'))setDetail('events');}setShowIssues(false);}}><b>{i.severity==='error'?'À corriger':'À vérifier'}</b> {i.message}<small>{i.path}</small></button>):<p>Aucune erreur détectée. Ce contrôle n’évalue pas la difficulté réelle d’une partie.</p>}</section>}
  {message&&<div className="gd-message" role="status"><span>{message}</span><button aria-label="Fermer le message des niveaux" onClick={()=>setMessage('')}>×</button></div>}
 </div>;
});
