import React from 'react';
import type { GameProject } from '../../shared/game/types.js';
import { newVariable,logicReferences,type VariableDefinition } from '../../shared/game/logic.js';
import { Select } from './LogicFields.js';
import { Num } from './BalanceEditor.js';
export function VariableEditor({project,change,report}:{project:GameProject;change:(f:(p:GameProject)=>void,key?:string,label?:string)=>void;report:(s:string)=>void}){
 const vars=project.logic!.variables;
 const patch=(id:string,v:Partial<VariableDefinition>,key='')=>change(p=>Object.assign(p.logic!.variables.find(x=>x.id===id)!,v),key?`var:${id}:${key}`:'','Modifier une variable');
 return <main className="gd-scroll logic-variable-main"><div className="gd-section-heading"><div><div className="gd-kicker">VARIABLES ET DRAPEAUX</div><h1>État du jeu</h1></div><button className="gd-primary" disabled={vars.length>=128} onClick={()=>change(p=>p.logic!.variables.push(newVariable()),'','Créer une variable')}>+ Variable</button></div><p className="gd-callout">Les variables de niveau repartent de leur valeur initiale à chaque nouvelle tentative. Les variables de campagne sont validées après une victoire sur l’étape en cours ; une défaite ou une lecture libre ne les modifie pas. Les compétences restent fixes.</p>
 {!vars.length&&<p>Aucune variable. Ajoute par exemple « boss_en_colere » (booléen) ou « pollution » (nombre).</p>}{vars.map(v=><section className="logic-card" key={v.id}><div className="logic-row"><label className="gd-field"><span>Nom de variable</span><input aria-label={'Nom variable '+v.id} maxLength={120} value={v.name} onChange={e=>patch(v.id,{name:e.target.value},'name')}/></label><code>{v.id}</code><button onClick={()=>{const refs=logicReferences(project,'variables',v.id);if(refs.length){report('Encore utilisée par : '+refs.join(', '));return;}change(p=>{p.logic!.variables=p.logic!.variables.filter(x=>x.id!==v.id);},'','Supprimer une variable');}}>Supprimer</button></div><div className="gd-form-grid"><Select label={'Portée '+v.name} value={v.scope} change={scope=>patch(v.id,{scope:scope as VariableDefinition['scope']})} options={[{id:'level',name:'Cette tentative du niveau'},{id:'campaign',name:'Campagne (après victoire)'}]}/><Select label={'Type '+v.name} value={v.type} change={type=>patch(v.id,{type:type as VariableDefinition['type'],minimum:0,maximum:type==='boolean'?1:100,initial:0})} options={[{id:'number',name:'Nombre'},{id:'boolean',name:'Booléen (vrai / faux)'}]}/>{v.type==='boolean'?<Select label={'Valeur initiale '+v.name} value={String(v.initial)} change={n=>patch(v.id,{initial:Number(n)})} options={[{id:'0',name:'Faux'},{id:'1',name:'Vrai'}]}/>:<><Num label={'Initiale '+v.name} value={v.initial} min={-1000000} max={1000000} change={initial=>patch(v.id,{initial})}/><Num label={'Minimum '+v.name} value={v.minimum} min={-1000000} max={1000000} change={minimum=>patch(v.id,{minimum})}/><Num label={'Maximum '+v.name} value={v.maximum} min={-1000000} max={1000000} change={maximum=>patch(v.id,{maximum})}/></>}</div><p className="gd-note">Utilisée par : {logicReferences(project,'variables',v.id).join(', ')||'aucune règle'}</p></section>)}
 </main>;
}
