import React, { useEffect, useState } from 'react';
import { activeEnemies, enemyChoices, DEFAULT_WAVE_SEED_REWARD, newId, waveSchedule, replaceWaves, type WaveDefinition, type LevelDefinition, type EnemyDefinition, type SpawnGroup, type SpawnArea } from '../../shared/game/types.js';
import { Num } from './BalanceEditor.js';
export function WaveEditor({level,enemies,update}:{level:LevelDefinition;enemies:EnemyDefinition[];update:(patch:Partial<LevelDefinition>,key?:string)=>void}){
 const [waveId,setWaveId]=useState(level.waves[0].id),[time,setTime]=useState(0),[playing,setPlaying]=useState(false);
 const wave=level.waves.find(w=>w.id===waveId)??level.waves[0],schedule=waveSchedule(wave),end=Math.max(1,(schedule.at(-1)?.at??0)+2),available=activeEnemies(enemies);
 useEffect(()=>{setTime(0);setPlaying(false);},[wave.id]);
 useEffect(()=>{setTime(t=>Math.min(t,end));},[end]);
 useEffect(()=>{if(!playing)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(.1,(now-last)/1000);last=now;setTime(t=>Math.min(end,t+dt));frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,end]);
 useEffect(()=>{if(time>=end)setPlaying(false);},[time,end]);
 const edit=(fn:(w:WaveDefinition)=>void,key='')=>{const waves=structuredClone(level.waves);fn(waves.find(w=>w.id===wave.id)!);update({waves},key);};
 const patch=(id:string,part:Partial<SpawnGroup>,key='')=>edit(w=>{const group=w.groups.find(g=>g.id===id)!;Object.assign(group,part);if(Object.hasOwn(part,'placement')&&part.placement===undefined)delete group.placement;},key);
 const patchArea=(g:SpawnGroup,part:Partial<SpawnArea>)=>patch(g.id,{placement:{...g.placement!,...part}});
 const addWave=()=>{if(!available.length)return;const next:WaveDefinition={id:newId('wave'),seedReward:DEFAULT_WAVE_SEED_REWARD,groups:[{id:newId('group'),enemyId:available[0].id,count:5,lane:-1,start:0,interval:3}]};update({waves:[...level.waves,next]});setWaveId(next.id);};
 const duplicate=()=>{const next=structuredClone(wave);next.id=newId('wave');next.groups.forEach(g=>g.id=newId('group'));const waves=[...level.waves];waves.splice(waves.findIndex(w=>w.id===wave.id)+1,0,next);update(replaceWaves(level,waves));setWaveId(next.id);};
 return <section className="gd-waves">
   <div className="gd-wave-tabs" role="tablist" aria-label="Vagues">{level.waves.map((w,i)=><button key={w.id} role="tab" aria-selected={wave.id===w.id} className={wave.id===w.id?'selected':''} onClick={()=>setWaveId(w.id)}>Vague {i+1}<small>{w.groups.reduce((n,g)=>n+g.count,0)} ennemis</small></button>)}<button disabled={level.waves.length>=50||!available.length} onClick={addWave}>+ Vague</button></div>
  <div className="gd-section-heading"><div><h2>Composition de la vague</h2><p><strong>{schedule.length} ennemis prévus{level.objective.type==='advance'?' maximum':''}</strong> · Dernière arrivée à {(end-2).toFixed(1)} s</p></div><div className="gd-inline"><button onClick={duplicate} disabled={level.waves.length>=50}>Dupliquer la vague</button><button disabled={level.waves.length===1} onClick={()=>update(replaceWaves(level,level.waves.filter(w=>w.id!==wave.id)))}>Retirer la vague</button></div></div>
  {level.objective.type==='advance'&&<p className="gd-note">En aléatoire, les ennemis sont répartis équitablement entre les cinq allées. Une allée conquise annule ses futures arrivées, sans les reporter ailleurs. Avec quatre allées conquises, il reste environ 20 % des ennemis prévus.</p>}
  <div className="gd-wave-reward"><Num label="Graines pour la vague éliminée" value={wave.seedReward??DEFAULT_WAVE_SEED_REWARD} max={10000} integer change={v=>edit(w=>{w.seedReward=v;},`${wave.id}:seedReward`)}/><p>Versées une fois lorsque tous les ennemis de cette vague ont été éliminés. Aucune prime si un ennemi s’échappe. La récompense par ennemi reste indépendante.</p></div>
  <div className="gd-wave-table"><div className="gd-wave-head"><span>Ennemi</span><span>Nombre</span><span>Allée / position</span><span>Délai (s)</span><span>Intervalle (s)</span><span/></div>
   {wave.groups.map((g,i)=><div className="gd-spawn-entry" key={g.id}><div className="gd-spawn-row">
     <select aria-label={`Ennemi du groupe ${i+1}`} value={g.enemyId} onChange={e=>{const enemyId=e.target.value;patch(g.id,enemyId==='plaque'?{enemyId,lane:-1,placement:{rowMin:2,rowMax:2,colMin:6,colMax:6}}:{enemyId,placement:undefined});}}>{enemyChoices(enemies,g.enemyId).map(e=><option value={e.id} key={e.id}>{e.name}{e.archived?' (archivé)':''}</option>)}</select>
    <Num label={`Nombre du groupe ${i+1}`} value={g.count} min={1} max={256} integer change={v=>patch(g.id,{count:v})}/>
    {g.enemyId==='plaque'?<span className="gd-spawn-position">Case / zone ci-dessous</span>:<select aria-label={`Allée du groupe ${i+1}`} value={g.lane} onChange={e=>patch(g.id,{lane:Number(e.target.value)})}><option value={-1}>{level.objective.type==='advance'?'Aléatoire équilibré':'Aléatoire'}</option>{[0,1,2,3,4].map(n=><option key={n} value={n}>Allée {n+1}</option>)}</select>}
    <Num label={`Début du groupe ${i+1}`} value={g.start} max={600} change={v=>patch(g.id,{start:v})}/>
    <Num label={`Intervalle du groupe ${i+1}`} value={g.interval} min={.1} max={120} change={v=>patch(g.id,{interval:v})}/>
    <button aria-label={`Retirer le groupe ${i+1}`} disabled={wave.groups.length===1} onClick={()=>edit(w=>{w.groups=w.groups.filter(x=>x.id!==g.id);})}>×</button>
   </div>
   {g.enemyId==='plaque'&&g.placement&&<div className="gd-plaque-placement"><label>Apparition
    <select aria-label={`Mode d’apparition de la Plaque du groupe ${i+1}`} value={g.placement.rowMin===g.placement.rowMax&&g.placement.colMin===g.placement.colMax?'cell':'zone'} onChange={e=>{if(e.target.value==='cell')patchArea(g,{rowMax:g.placement!.rowMin,colMax:g.placement!.colMin});else patchArea(g,{rowMin:Math.max(0,g.placement!.rowMin-1),rowMax:Math.min(4,g.placement!.rowMin+1),colMin:Math.max(0,g.placement!.colMin-1),colMax:Math.min(7,g.placement!.colMin+1)});}}><option value="cell">Case précise</option><option value="zone">Case aléatoire dans une zone</option></select>
   </label><Num label="Allée de départ" value={g.placement.rowMin+1} min={1} max={5} integer change={v=>patchArea(g,{rowMin:v-1,rowMax:g.placement!.rowMin===g.placement!.rowMax&&g.placement!.colMin===g.placement!.colMax?v-1:Math.max(v-1,g.placement!.rowMax)})}/><Num label="Colonne de départ" value={g.placement.colMin+1} min={1} max={8} integer change={v=>patchArea(g,{colMin:v-1,colMax:g.placement!.rowMin===g.placement!.rowMax&&g.placement!.colMin===g.placement!.colMax?v-1:Math.max(v-1,g.placement!.colMax)})}/>
   {(g.placement.rowMin!==g.placement.rowMax||g.placement.colMin!==g.placement.colMax)&&<><Num label="Allée de fin" value={g.placement.rowMax+1} min={g.placement.rowMin+1} max={5} integer change={v=>patchArea(g,{rowMax:v-1})}/><Num label="Colonne de fin" value={g.placement.colMax+1} min={g.placement.colMin+1} max={8} integer change={v=>patchArea(g,{colMax:v-1})}/></>}
   <p>La Plaque surgit après le délai indiqué depuis le début de cette vague. Elle reste sur place, crache vers une plante de son allée et fait arriver une Canette pressée dans cette même allée toutes les 10 secondes, même sans cible. La première canette arrive 10 secondes après son apparition ; sa destruction arrête les renforts.</p></div>}
   </div>)}
  </div>
   <button className="gd-add" disabled={wave.groups.length>=256||!available.length} onClick={()=>edit(w=>w.groups.push({id:newId('group'),enemyId:available[0].id,count:3,lane:-1,start:0,interval:3}))}>+ Ajouter un groupe d’ennemis</button>
  <section className="gd-preview"><div className="gd-section-heading"><div><h2>Aperçu des arrivées</h2><p>Prévisualisation du planning, pas une simulation du combat. Les allées aléatoires sont indiquées par « ? ».{level.objective.type==='advance'?' Toutes les allées sont ouvertes dans cet aperçu ; le jeu annule les arrivées des allées conquises.':''}</p></div><button onClick={()=>{if(time>=end)setTime(0);setPlaying(!playing);}}>{playing?'Pause':'Lire les arrivées'}</button></div>
   <svg viewBox="0 0 800 190" role="img" aria-label="Planning d’apparition sur les cinq allées">
    {[0,1,2,3,4].map(n=><g key={n}><rect x={72} y={n*30+8} width={714} height={27} rx={4} fill={n%2?'#233729':'#1c3023'}/><text x={8} y={n*30+27} fill="#b9caae" fontSize={12}>Allée {n+1}</text></g>)}
    {schedule.map((s,i)=>{const row=s.placement?(s.placement.rowMin+s.placement.rowMax)/2:(s.lane<0?i%5:s.lane),random=s.placement?s.placement.rowMin!==s.placement.rowMax||s.placement.colMin!==s.placement.colMax:s.lane<0,x=82+s.at/end*690;return <g key={i}>{s.placement&&s.placement.rowMax>s.placement.rowMin&&<rect x={x-4} y={s.placement.rowMin*30+15} width={8} height={(s.placement.rowMax-s.placement.rowMin)*30+12} rx={4} fill="#8fae80" opacity={.5}/>}<circle cx={x} cy={row*30+21} r={s.at<=time?5:3} fill={s.at<=time?'#dfc785':'#648361'}/>{random&&<text x={x-3} y={row*30+25} fontSize={9} fill="#15281c">?</text>}<title>{enemies.find(e=>e.id===s.enemyId)?.name} · {s.at.toFixed(1)} s{s.placement?` · allées ${s.placement.rowMin+1}–${s.placement.rowMax+1}, colonnes ${s.placement.colMin+1}–${s.placement.colMax+1}`:''}</title></g>;})}
    <line x1={82+time/end*690} x2={82+time/end*690} y1={0} y2={160} stroke="#f4e3b1" strokeWidth={2}/><text x={72} y={182} fill="#9eb497" fontSize={12}>0 s</text><text x={723} y={182} fill="#9eb497" fontSize={12}>{end.toFixed(1)} s</text>
   </svg>
   <div className="gd-inline"><input aria-label="Temps de l’aperçu des arrivées" type="range" min={0} max={end} step={.05} value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><output>{time.toFixed(1)} s · {schedule.filter(x=>x.at<=time).length}/{schedule.length}</output></div>
  </section>
 </section>;
}
