import React from 'react';
import type {Asset,Actor,Cinematic} from '../../shared/model.js';
import type {GameProject} from '../../shared/game/types.js';
import type {Cue,AbilityPresentation,ProjectilePresentation,ActorAnimation,CatalogLink} from '../../shared/presentation/types.js';
import {BASE_SLOTS,DEFAULT_ABILITY_PRESENTATION,EMPTY_CUE} from '../../shared/presentation/types.js';
import {Num} from '../game/BalanceEditor.js';
export function Choose({label,value,options,change,empty=false}:{label:string;value:string;options:{id:string;name:string}[];change:(v:string)=>void;empty?:boolean}){return <label className="gd-field field"><span>{label}</span><select aria-label={label} value={value} onChange={e=>change(e.target.value)}>{empty&&<option value="">Aucun / hériter</option>}{value&&!options.some(x=>x.id===value)&&<option value={value}>{value} — introuvable</option>}{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;}
export function AssetChoice({label,value,assets,audio=false,empty=false,change}:{label:string;value:string;assets:Asset[];audio?:boolean;empty?:boolean;change:(ref:string)=>void}){return <Choose label={label} value={value} empty={empty} options={assets.filter(a=>(audio?/\.(wav|ogg|mp3)$/i:/\.(png|jpg|jpeg|webp)$/i).test(a.path)).map(a=>({id:a.ref,name:a.path}))} change={change}/>;}
export function CueFields({label,project,value,change}:{label:string;project:GameProject;value:Cue;change:(v:Cue)=>void}){const c=project.presentation!;return <fieldset className="lp-cue"><legend>{label}</legend><Choose label="Son" value={value.soundId} options={c.audio} empty change={soundId=>change({...value,soundId})}/><Choose label="VFX" value={value.vfxId} options={c.vfx} empty change={vfxId=>change({...value,vfxId})}/><Choose label="Point d’attache" value={value.attach} options={['center','feet','head','launch'].map(id=>({id,name:id}))} change={attach=>change({...value,attach:attach as Cue['attach']})}/></fieldset>;}
export function AbilityPresentationFields({project,value,change}:{project:GameProject;value?:AbilityPresentation;change:(v:AbilityPresentation)=>void}){const p=value??DEFAULT_ABILITY_PRESENTATION;return <section><h2>Présentation</h2><p>La capacité demande un slot ; chaque espèce choisit sa propre animation. Le délai de libération est calculé par la simulation, même sans affichage.</p><label className="gd-field"><span>Slot sémantique demandé</span><input aria-label="Slot sémantique demandé" list="lp-semantic-slots" value={p.slot} onChange={e=>change({...p,slot:e.target.value})}/><datalist id="lp-semantic-slots">{BASE_SLOTS.map(s=><option key={s} value={s}/>)}</datalist></label><div className="gd-form-grid"><Choose label="Libération" value={p.release} options={[{id:'marker',name:'Marqueur release (sinon délai)'},{id:'delay',name:'Délai explicite'},{id:'immediate',name:'Immédiate'}]} change={release=>change({...p,release:release as AbilityPresentation['release']})}/><Num label="Délai / repli sans marqueur (s)" value={p.delay} min={0} max={120} change={delay=>change({...p,delay})}/></div><label><input type="checkbox" checked={p.fitCadence} onChange={e=>change({...p,fitCadence:e.target.checked})}/> Accélérer l’animation et sa libération si la cadence est plus courte</label><p className="gd-note">La mort annule les préparations. L’étourdissement les annule sans les rejouer à la reprise. Les capacités simultanées gardent chacune leur libération ; la première conserve le geste visible. Touché est une superposition locale.</p>{(['start','releaseCue','impact'] as const).map((key,i)=><CueFields key={key} project={project} value={p[key]} label={['Préparation','Libération','Impact'][i]} change={v=>change({...p,[key]:v})}/>)}</section>;}
export function ProjectilePresentationFields({project,value,assets,change}:{project:GameProject;value?:ProjectilePresentation;assets:Asset[];change:(v:ProjectilePresentation)=>void}){const p=value??{asset:'',animationId:'',trailVfxId:'',impact:{...EMPTY_CUE,attach:'center'}};return <section><h2>Présentation du projectile</h2><AssetChoice label="Image du projectile (vide : forme simple)" value={p.asset} assets={assets} empty change={asset=>change({...p,asset:asset as ProjectilePresentation['asset']})}/><Choose label="Animation du projectile" value={p.animationId} options={project.presentation!.animations} empty change={animationId=>change({...p,animationId})}/><Choose label="Traînée visuelle" value={p.trailVfxId} options={project.presentation!.vfx} empty change={trailVfxId=>change({...p,trailVfxId})}/><CueFields label="Impact (repli après le profil et la capacité)" project={project} value={p.impact} change={impact=>change({...p,impact})}/></section>;}
export function ActorBindingFields({actor,doc,project,change,setCatalog}:{actor:Actor;doc:Cinematic;project:GameProject;change:(patch:Partial<Actor>)=>void;setCatalog:(value:CatalogLink)=>void}){
 const binding=actor.animation,all=[...project.balance.plants,...project.balance.enemies];const fallback:ActorAnimation={mode:'species',speciesId:all[0].id,slot:'idle',animationId:'',speed:1};
 const set=(p:ActorAnimation)=>{setCatalog({projectId:project.id,file:doc.presentationCatalog?.projectId===project.id?doc.presentationCatalog.file:''});change({animation:p});};
 return <section><h3>Animation partagée</h3><Choose label="Source de l’acteur" value={binding?.mode??'static'} options={[{id:'static',name:'Image fixe'},{id:'species',name:'Espèce → profil → slot'},{id:'animation',name:'Animation du catalogue'}]} change={mode=>{if(mode==='static')change({animation:undefined});else set({...binding??fallback,mode:mode as ActorAnimation['mode'],animationId:binding?.animationId||project.presentation!.animations[0].id});}}/>{binding&&<><p className="field-hint">Catalogue : {doc.presentationCatalog?.projectId??'non relié'}. Ouvre le projet correspondant dans Niveaux. Aucun marqueur ne provoque une attaque.</p>{doc.presentationCatalog?.projectId!==project.id&&<p role="alert">Le catalogue du film ne correspond pas au projet ouvert.</p>}<Choose label={binding.mode==='species'?'Espèce animée':'Espèce de repos (animation procédurale)'} value={binding.speciesId} options={all} empty={binding.mode==='animation'} change={speciesId=>set({...binding,speciesId})}/>{binding.mode==='animation'?<Choose label="Animation partagée" value={binding.animationId} options={project.presentation!.animations} change={animationId=>set({...binding,animationId})}/>:<label className="field"><span>Slot de l’acteur</span><input value={binding.slot} onChange={e=>set({...binding,slot:e.target.value})}/></label>}<Num label="Vitesse de lecture" value={binding.speed} min={.05} max={10} change={speed=>set({...binding,speed})}/><label className="field"><span>Fichier du catalogue, relatif au projet publié</span><input value={doc.presentationCatalog?.file??''} placeholder="content/design/game_content.json" onChange={e=>setCatalog({projectId:project.id,file:e.target.value})}/></label></>}</section>;
}
