import {VfxGlyph} from './CuePrimitives.js';
import {gameAPI} from '../game/bridge.js';
import React,{useEffect,useRef,useState} from 'react';
import type {Asset} from '../../shared/model.js';
import type {GameProject} from '../../shared/game/types.js';
import {newId} from '../../shared/game/types.js';
import {DEFAULT_PRESENTATION,newAnimation} from '../../shared/presentation/defaults.js';
import {animationUsages,duration} from '../../shared/presentation/runtime.js';
import {BASE_SLOTS,MOTIONS,EMPTY_CUE,SLOT_LABELS,type PresentationSection,type AnimationDefinition,type AnimationFrame,type AnimationProfile,type SoundDefinition,type VfxDefinition,type EventCue} from '../../shared/presentation/types.js';
import {AnimationPreview,useImageSize} from './AnimationPreview.js';
import {Choose,AssetChoice,CueFields} from './PresentationFields.js';
import {Num} from '../game/BalanceEditor.js';
import {api} from '../browserBridge.js';
import './presentation.css';
const TITLES={animations:'Animations',profiles:'Profils d’animation',audio:'Audio',vfx:'VFX'};
export type Change=(edit:(p:GameProject)=>void,key?:string,label?:string)=>void;
interface Props{project:GameProject;section:PresentationSection;id:string;select:(id:string)=>void;assets:Asset[];change:Change;report:(s:string)=>void;run:(fn:()=>Promise<void>)=>Promise<void>;openAnimation:(id:string)=>void;externalUsages?:Record<string,string[]>}
export function PresentationEditor({project,section,id,select,assets,change,report,run,openAnimation,externalUsages={}}:Props){
 const [query,setQuery]=useState(''),c=project.presentation!,list=c[section],item=list.find(x=>x.id===id)??list[0];
 const [filmUses,setFilmUses]=useState<{references:Record<string,string[]>;errors:string[]}>({references:{},errors:[]}),[checking,setChecking]=useState(false);
 const refreshUses=async()=>{setChecking(true);try{setFilmUses(await gameAPI.presentationUsages(project));}catch(e){setFilmUses({references:{},errors:[String(e)]});}finally{setChecking(false);}};
 const filmKey=JSON.stringify(project.campaign?.cinematics??[]);
 useEffect(()=>{let live=true;setChecking(true);void gameAPI.presentationUsages(project).then(r=>{if(live)setFilmUses(r);},e=>{if(live)setFilmUses({references:{},errors:[String(e)]});}).finally(()=>{if(live)setChecking(false);});return()=>{live=false;};},[project.id,filmKey]);
 const refs=item?[...animationUsages(project,section,item.id),...(externalUsages[item.id]??[]),...(filmUses.references[item.id]??[])]:[];
 const patch=(data:Record<string,unknown>,key='')=>item&&change(p=>Object.assign(p.presentation![section].find(x=>x.id===item.id)!,data),`${item.id}:${key}`,'Modifier '+TITLES[section]);
 function create(){let value:AnimationDefinition|AnimationProfile|SoundDefinition|VfxDefinition;if(section==='animations')value=newAnimation();else if(section==='profiles')value={id:newId('profile'),name:'Nouveau profil',slots:[],events:[]};else if(section==='audio'){const asset=assets.find(x=>/\.(wav|ogg|mp3)$/i.test(x.path));if(!asset){report('Relie la bibliothèque contenant les sons dans le mode Cinématiques. Aucun fichier audio n’a été inventé.');return;}value={id:newId('sound'),name:'Nouveau son',asset:asset.ref,bus:'sfx',volume:.6,loop:false,pitchVariation:0,maxInstances:4};}else value={id:newId('vfx'),name:'Nouvel effet visuel',preset:'impact',duration:.35,size:32,color:'#b0db90',intensity:.7,quantity:8,asset:'',attach:'center',maxInstances:12};change(p=>(p.presentation![section] as typeof list).push(value as never),'','Créer '+TITLES[section]);select(value.id);}
 function duplicate(){if(!item)return;const value=structuredClone(item);value.id=newId(section);value.name=(item.name+' — copie').slice(0,160);change(p=>(p.presentation![section] as typeof list).push(value as never),'','Dupliquer '+item.name);select(value.id);}
 async function remove(){if(!item)return;if(refs.length){report('Suppression impossible : '+refs.join(', '));return;}await run(async()=>{const fresh=await gameAPI.presentationUsages(project);setFilmUses(fresh);if(fresh.errors.length)throw Error('Suppression bloquée : les usages des films liés ne peuvent pas être vérifiés. '+fresh.errors.join('; '));if((fresh.references[item.id]??[]).length)throw Error('Cette animation est utilisée par '+fresh.references[item.id].join(', '));if(!await api.confirmDelete(item.name))return;change(p=>{const current=animationUsages(p,section,item.id);if(current.length)throw Error('La définition est encore utilisée.');(p.presentation![section] as typeof list).splice(p.presentation![section].findIndex(x=>x.id===item.id),1);},'','Supprimer '+item.name);});}
 return <div className="gd-balance lp-editor"><aside className="gd-catalog"><input aria-label="Rechercher une présentation" placeholder="Rechercher…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={create}>+ Créer</button>{list.filter(x=>(x.name+' '+x.id).toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(x=><button key={x.id} className={x.id===item?.id?'selected':''} onClick={()=>select(x.id)}><b>{x.name}</b><small>{x.id}</small></button>)}</aside><main className="gd-scroll gd-balance-form" key={item?.id??section}><h1>{TITLES[section]}</h1>{item?<><div className="gd-inline"><button onClick={duplicate}>Dupliquer avant de personnaliser</button><button disabled={checking||filmUses.errors.length>0||refs.length>0||(section==='profiles'&&c.profiles.length===1)} onClick={()=>void remove()}>Supprimer</button></div><label className="gd-field"><span>Nom</span><input aria-label="Nom de la présentation" value={item.name} maxLength={160} onChange={e=>patch({name:e.target.value},'name')}/></label><small>Identifiant stable : {item.id}</small><details className="gd-callout"><summary>{refs.length} référence(s) concernée(s) par cette modification</summary>{refs.map((r,i)=><p key={i}>{r}</p>)}<button disabled={checking} onClick={()=>void refreshUses()}>Actualiser les usages des films liés</button>{filmUses.errors.map((e,i)=><p key={'error'+i} role="alert">{e} — suppression bloquée.</p>)}<p>Les usages du projet, du film ouvert et des films liés sont protégés ; la publication les revalide.</p></details>{section==='animations'?<AnimationFields value={item as AnimationDefinition} project={project} assets={assets} patch={patch}/>:section==='profiles'?<ProfileFields value={item as AnimationProfile} project={project} assets={assets} patch={patch} openAnimation={openAnimation}/>:section==='audio'?<AudioFields value={item as SoundDefinition} assets={assets} patch={patch}/>:<VfxFields value={item as VfxDefinition} assets={assets} patch={patch}/>}</>:<p>Ce catalogue est vide. Crée une première définition ; l’absence de son est un choix valide.</p>}</main></div>;
}
function AnimationFields({value:a,project,assets,patch}:{value:AnimationDefinition;project:GameProject;assets:Asset[];patch:(p:Record<string,unknown>,key?:string)=>void}){
 const [frameIndex,setFrameIndex]=useState(0),[atlas,setAtlas]=useState(''),[columns,setColumns]=useState(4),[rows,setRows]=useState(1),[previewSpecies,setPreviewSpecies]=useState(project.balance.plants[0].id),[fps,setFps]=useState(12);
 const selected=a.frames[frameIndex],all=[...project.balance.plants,...project.balance.enemies],visual=all.find(x=>x.id===previewSpecies)?.visual,atlasAsset=assets.find(x=>x.ref===atlas),atlasSize=useImageSize(atlasAsset?.url??'');
 const updateFrame=(data:Record<string,unknown>)=>patch({frames:a.frames.map((f,i)=>i===frameIndex?{...f,...data}:f)},'frame'+frameIndex);
 const newFrame=(ref:string)=>{patch({kind:a.kind==='procedural'?'combined':a.kind,frames:[...a.frames,{asset:ref,duration:1/fps}]},'');setFrameIndex(a.frames.length);};
 const move=(by:number)=>{const to=frameIndex+by;if(to<0||to>=a.frames.length)return;const frames=structuredClone(a.frames);[frames[frameIndex],frames[to]]=[frames[to],frames[frameIndex]];patch({frames});setFrameIndex(to);};
 return <><div className="lp-columns"><div><Choose label="Type d’animation" value={a.kind} options={[{id:'procedural',name:'Procédurale (sprite de l’espèce)'},{id:'frames',name:'Séquence / planche de sprites'},{id:'combined',name:'Sprites + transformation'}]} change={kind=>patch({kind,frames:kind==='procedural'?[]:a.frames})}/><Choose label="Personnage de prévisualisation" value={previewSpecies} options={all} change={setPreviewSpecies}/><label><input type="checkbox" checked={a.loop} onChange={e=>patch({loop:e.target.checked})}/> Boucle (interdite pour attaque, touché et mort)</label>{a.kind==='procedural'&&<Num label="Durée (s)" value={a.duration} min={.01} max={120} change={duration=>patch({duration})}/>}<Choose label="Préréglage de transformation" value={a.motion.preset} options={MOTIONS.map(id=>({id,name:id}))} change={preset=>patch({motion:{...a.motion,preset}})}/><Num label="Amplitude" value={a.motion.amplitude} max={5} change={amplitude=>patch({motion:{...a.motion,amplitude}})}/><Num label="Période (s)" value={a.motion.period} min={.05} max={120} change={period=>patch({motion:{...a.motion,period}})}/></div><AnimationPreview catalog={project.presentation} animation={a} visual={visual} assets={assets}/></div>
 {a.kind!=='procedural'&&<section><h2>Images / régions sans copie des PNG</h2><div className="gd-inline lp-frames">{a.frames.map((f,i)=><button key={i} className={i===frameIndex?'selected':''} onClick={()=>setFrameIndex(i)}>{i+1} · {f.duration.toFixed(3)} s</button>)}</div><div className="gd-form-grid"><AssetChoice label="Ajouter une image" value="" assets={assets} empty change={ref=>{if(ref&&a.frames.length<512)newFrame(ref);}}/><Num label="Vitesse (images/s)" value={fps} min={1} max={100} change={setFps}/><button disabled={!a.frames.length} onClick={()=>patch({frames:a.frames.map(f=>({...f,duration:1/fps}))})}>Appliquer la vitesse aux frames</button></div>{selected&&<fieldset className="lp-cue"><legend>Frame {frameIndex+1}</legend><AssetChoice label="PNG / atlas" value={selected.asset} assets={assets} change={asset=>updateFrame({asset})}/><Num label="Durée de cette frame (s)" value={selected.duration} min={.01} max={60} change={duration=>updateFrame({duration})}/><div className="gd-inline"><button disabled={frameIndex===0} onClick={()=>move(-1)}>Monter</button><button disabled={frameIndex>=a.frames.length-1} onClick={()=>move(1)}>Descendre</button><button onClick={()=>{patch({frames:a.frames.filter((_,i)=>i!==frameIndex)});setFrameIndex(Math.max(0,frameIndex-1));}}>Retirer</button></div><label><input type="checkbox" checked={!!selected.region} onChange={e=>updateFrame({region:e.target.checked?{x:0,y:0,width:64,height:64}:undefined})}/> Rectangle de découpe</label>{selected.region&&<div className="gd-form-grid">{(['x','y','width','height'] as const).map(k=><Num key={k} label={'Région '+k} value={selected.region![k]} min={k==='width'||k==='height'?1:0} max={32768} integer change={v=>updateFrame({region:{...selected.region,[k]:v}})}/>)}</div>}<label><input type="checkbox" checked={!!selected.anchor} onChange={e=>updateFrame({anchor:e.target.checked?{...a.anchor}:undefined})}/> Ancrage propre à la frame (pieds mesurés)</label>{selected.anchor&&<div className="gd-form-grid">{(['x','y'] as const).map(k=><Num key={k} label={'Ancrage frame '+k} value={selected.anchor![k]} min={-2} max={3} change={v=>updateFrame({anchor:{...selected.anchor,[k]:v}})}/>)}</div>}</fieldset>}
 <details><summary>Importer une grille régulière</summary><AssetChoice label="Planche de sprites" value={atlas} assets={assets} empty change={setAtlas}/><div className="gd-form-grid"><Num label="Colonnes" value={columns} min={1} max={64} integer change={setColumns}/><Num label="Lignes" value={rows} min={1} max={64} integer change={setRows}/></div>{atlasSize&&<small>{atlasSize.width} × {atlasSize.height} pixels. Les régions restent des métadonnées.</small>}<button disabled={!atlasSize||columns*rows>512||a.frames.length+columns*rows>512} onClick={()=>{if(!atlasSize)return;const frames:AnimationFrame[]=[];for(let y=0;y<rows;y++)for(let x=0;x<columns;x++){const left=Math.floor(x*atlasSize.width/columns),top=Math.floor(y*atlasSize.height/rows);frames.push({asset:atlas as `library://${string}`,duration:1/fps,region:{x:left,y:top,width:Math.floor((x+1)*atlasSize.width/columns)-left,height:Math.floor((y+1)*atlasSize.height/rows)-top}});}patch({frames:[...a.frames,...frames]});}}>Ajouter les régions de la grille</button></details></section>}
 <details><summary>Ancrage et transformations locales</summary><div className="gd-form-grid">{(['x','y'] as const).map(k=><Num key={k} label={'Ancrage '+k} value={a.anchor[k]} min={-2} max={3} change={v=>patch({anchor:{...a.anchor,[k]:v}})}/>)}{(['x','y','rotation','scaleX','scaleY','opacity'] as const).map(k=><Num key={k} label={'Transformation '+k} value={a.transform[k]} min={k==='opacity'?0:k.startsWith('scale')?.01:k==='rotation'?-720:-200} max={k==='opacity'?1:k.startsWith('scale')?5:k==='rotation'?720:200} change={v=>patch({transform:{...a.transform,[k]:v}})}/>)}</div><h3>Points d’attache normalisés</h3>{a.attachments.map((p,i)=><div className="gd-form-grid" key={p.id}><b>{p.id}</b>{(['x','y'] as const).map(k=><Num key={k} label={p.id+' '+k} value={p[k]} min={-2} max={3} change={v=>patch({attachments:a.attachments.map((q,j)=>j===i?{...q,[k]:v}:q)})}/>)}</div>)}</details>
 <h2>Marqueurs typés</h2><p>release synchronise une attaque. Son et VFX ne modifient jamais le gameplay. Le curseur d’aperçu ne les exécute pas.</p>{a.markers.map((m,i)=><fieldset className="lp-marker" key={m.id}><Choose label="Type de marqueur" value={m.type} options={['release','sound','vfx'].map(id=>({id,name:id}))} change={type=>patch({markers:a.markers.map((x,j)=>j===i?{...x,type,ref:''}:x)})}/><input aria-label={'Instant '+m.id} type="range" min={0} max={Math.max(.01,duration(a))} step={.001} value={Math.min(m.at,duration(a))} onChange={e=>patch({markers:a.markers.map((x,j)=>j===i?{...x,at:+e.target.value}:x)},m.id)}/><Num label="Instant (s)" value={m.at} min={0} max={Math.max(.01,duration(a))} change={at=>patch({markers:a.markers.map((x,j)=>j===i?{...x,at}:x)})}/>{m.type!=='release'&&<Choose label="Définition associée" value={m.ref} options={m.type==='sound'?project.presentation!.audio:project.presentation!.vfx} empty change={ref=>patch({markers:a.markers.map((x,j)=>j===i?{...x,ref}:x)})}/>}<Choose label="Attache du marqueur" value={m.attach} options={['center','feet','head','launch'].map(id=>({id,name:id}))} change={attach=>patch({markers:a.markers.map((x,j)=>j===i?{...x,attach}:x)})}/><button onClick={()=>patch({markers:a.markers.filter((_,j)=>j!==i)})}>Retirer</button></fieldset>)}<button disabled={a.markers.length>=64} onClick={()=>patch({markers:[...a.markers,{id:newId('marker'),type:a.markers.some(m=>m.type==='release')?'vfx':'release',at:duration(a)*.5,ref:'',attach:'launch'}]})}>+ Marqueur</button>
 </>;
}
export function ProfileFields({value,project,assets,patch,openAnimation}:{value:AnimationProfile;project:GameProject;assets:Asset[];patch:(p:Record<string,unknown>,key?:string)=>void;openAnimation:(id:string)=>void}){
 const [custom,setCustom]=useState('');const c=project.presentation!,fallback=c.profiles.find(p=>p.id===c.defaultProfileId),owner=[...project.balance.plants,...project.balance.enemies].find(s=>s.animationProfileId===value.id);
 const slots=[...new Set([...BASE_SLOTS,...(fallback?.slots??[]).map(s=>s.slot),...value.slots.map(s=>s.slot)])];
 const setSlot=(slot:string,animationId:string|null)=>patch({slots:animationId===null?value.slots.filter(s=>s.slot!==slot):[...value.slots.filter(s=>s.slot!==slot),{slot,animationId}]});
 return <><p>Les slots absents héritent du profil par défaut « {fallback?.name} ». La suppression d’une liaison restaure cet héritage.</p><div className="lp-slots">{slots.map(slot=>{const own=value.slots.find(s=>s.slot===slot),id=(own??fallback?.slots.find(s=>s.slot===slot))?.animationId,animation=c.animations.find(a=>a.id===id);return <article key={slot}><h3>{SLOT_LABELS[slot]??slot}</h3><AnimationPreview catalog={project.presentation} compact animation={animation} visual={owner?.visual??project.balance.plants[0].visual} assets={assets}/><Choose label={'Animation '+slot} value={id??''} options={c.animations} empty change={id=>setSlot(slot,id)}/><small>{own?'Liaison explicite':'Valeur par défaut'}</small><div className="gd-inline"><button disabled={!animation} onClick={()=>openAnimation(id!)}>Éditer →</button><button disabled={value.id===c.defaultProfileId} onClick={()=>setSlot(slot,null)}>Réglage par défaut</button></div></article>;})}</div><div className="gd-inline"><input aria-label="Nouveau slot personnalisé" placeholder="attack_special_01" value={custom} onChange={e=>setCustom(e.target.value)}/><button disabled={!/^[a-zA-Z0-9_-]+$/.test(custom)||slots.includes(custom)||value.slots.length>=32} onClick={()=>{setSlot(custom,'');setCustom('');}}>Ajouter le slot</button></div><h2>Événements propres au profil</h2><p>Un champ renseigné ici est prioritaire sur l’attaque, le tir et le profil par défaut. Le champ vide hérite. Aucun son n’est joué si toute la chaîne est vide.</p>{(['spawn','start','release','impact','death','phase_transition'] as const).map(event=><CueFields key={event} label={event} project={project} value={value.events.find(e=>e.event===event)??{...EMPTY_CUE,attach:'center'}} change={cue=>patch({events:[...value.events.filter(e=>e.event!==event),{...cue,event} as EventCue]})}/>)}<details><summary>Préréglage global</summary><button onClick={()=>patch({slots:structuredClone(DEFAULT_PRESENTATION.profiles.find(p=>p.id===DEFAULT_PRESENTATION.defaultProfileId)!.slots),events:[]})}>Copier les liaisons initiales (modification partagée)</button><p>La validation bloque une liaison dont l’animation a été supprimée.</p></details></>;
}
function AudioFields({value,assets,patch}:{value:SoundDefinition;assets:Asset[];patch:(p:Record<string,unknown>,key?:string)=>void}){
 const player=useRef<HTMLAudioElement|null>(null),[playing,setPlaying]=useState(false),[error,setError]=useState('');
 const stop=()=>{player.current?.pause();player.current=null;setPlaying(false);};useEffect(()=>{stop();return()=>player.current?.pause();},[value.id,value.asset]);
 useEffect(()=>{if(player.current){player.current.volume=value.volume;player.current.loop=value.loop;}},[value.volume,value.loop]);
 return <><AssetChoice label="Fichier audio de la bibliothèque" value={value.asset} audio assets={assets} change={asset=>patch({asset})}/><Choose label="Catégorie / volume du jeu" value={value.bus} options={[{id:'sfx',name:'Effets sonores'},{id:'music',name:'Musique'},{id:'ambience',name:'Ambiance (volume sonore)'}]} change={bus=>patch({bus})}/><div className="gd-form-grid"><Num label="Volume (0 à 1)" value={value.volume} max={1} change={volume=>patch({volume})}/><Num label="Variation de hauteur (±)" value={value.pitchVariation} max={.2} change={pitchVariation=>patch({pitchVariation})}/><Num label="Instances simultanées max." value={value.maxInstances} min={1} max={32} integer change={maxInstances=>patch({maxInstances})}/></div><label><input type="checkbox" checked={value.loop} onChange={e=>patch({loop:e.target.checked})}/> Boucle (arrêt à la disparition du porteur / de la scène)</label><p><button onClick={()=>{if(playing){stop();return;}const asset=assets.find(a=>a.ref===value.asset);if(!asset){setError('Fichier absent de la bibliothèque liée.');return;}const audio=new Audio(asset.url);player.current=audio;audio.volume=value.volume;audio.loop=value.loop;audio.playbackRate=1+(Math.random()*2-1)*value.pitchVariation;audio.onended=stop;void audio.play().then(()=>{setPlaying(true);setError('');}).catch(e=>{setError(String(e));stop();});}}>{playing?'Arrêter':'Écouter'}</button> {error}</p></>;
}
function VfxFields({value:v,assets,patch}:{value:VfxDefinition;assets:Asset[];patch:(p:Record<string,unknown>,key?:string)=>void}){
 const [time,setTime]=useState(0),[playing,setPlaying]=useState(false);useEffect(()=>{if(!playing)return;let handle=0,start=performance.now();const tick=(now:number)=>{const t=(now-start)/1000;setTime(t);if(t<v.duration)handle=requestAnimationFrame(tick);else setPlaying(false);};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[playing,v.duration]);
 const u=Math.min(1,time/v.duration),url=assets.find(a=>a.ref===v.asset)?.url;
 return <><Choose label="Préréglage VFX" value={v.preset} options={['impact','dust','leaves','halo','flash','explosion','trail'].map(id=>({id,name:id}))} change={preset=>patch({preset})}/><svg className="lp-vfx" viewBox="-180 -180 360 360"><VfxGlyph definition={v} age={time} assets={assets}/></svg><button onClick={()=>{setTime(0);setPlaying(true);}}>Prévisualiser le VFX</button><div className="gd-form-grid"><Num label="Durée VFX (s)" value={v.duration} min={.01} max={10} change={duration=>patch({duration})}/><Num label="Taille" value={v.size} min={1} max={300} change={size=>patch({size})}/><Num label="Intensité" value={v.intensity} max={1} change={intensity=>patch({intensity})}/><Num label="Quantité" value={v.quantity} min={1} max={64} integer change={quantity=>patch({quantity})}/><Num label="Instances VFX max." value={v.maxInstances} min={1} max={128} integer change={maxInstances=>patch({maxInstances})}/><label className="gd-field"><span>Couleur</span><input type="color" value={v.color} onChange={e=>patch({color:e.target.value})}/></label></div><Choose label="Attache par défaut" value={v.attach} options={['center','feet','head','launch'].map(id=>({id,name:id}))} change={attach=>patch({attach})}/><AssetChoice label="Image optionnelle" value={v.asset} assets={assets} empty change={asset=>patch({asset})}/><p>Ce VFX ne provoque ni dégât ni changement de vitesse. Les particules sont plafonnées ; la réduction des mouvements remplace les projections par un halo discret.</p></>;
}
